### ISSUE TITLE
Typo in the doxygen ?

### ISSUE THREAD

**Issue by ineol** [DGtal-team/DGtal#1003]
Line 236 of PointVector.h (https://github.com/DGtal-team/DGtal/blob/master/src/DGtal/kernel/PointVector.h#L236) reads "apoint" instead of "a point" or "any point".
Line 244 too.

**Comment by dcoeurjo** [comment]
Agree. It should be "taking two points and a BinaryFunctor and create a PointVector from the result of the binary functor applied to the two points"

**Comment by dcoeurjo** [comment]
PR #1004

**Comment by dcoeurjo** [comment]
donr
