### ISSUE TITLE
compile DGtal 0.8 failed under Mac OS X Yosemite

### ISSUE THREAD

**Issue by ngophuc** [DGtal-team/DGtal#1005]
I got these errors when compiling DGtal 0.8 (release version) : 
/DGtal-0.8/src/DGtal/base/IteratorCirculatorTraits.h:250: error: no template named 'iterator_category_with_traversal' in namespace 'boost::detail'; did you mean 'boost::iterators::detail::iterator_category_with_traversal'?
/DGtal-0.8/src/DGtal/base/IteratorCirculatorTraits.h:255: error: no template named 'iterator_category_with_traversal' in namespace 'boost::detail'; did you mean 'boost::iterators::detail::iterator_category_with_traversal'?
/DGtal-0.8/src/DGtal/base/IteratorCirculatorTraits.h:260: error: no template named 'iterator_category_with_traversal' in namespace 'boost::detail'; did you mean 'boost::iterators::detail::iterator_category_with_traversal'?

By changing "boost::detail::iterator_category_with_traversal" into "boost::iterators::detail::iterator_category_with_traversal" in the three lines 250, 255, 260 of  IteratorCirculatorTraits.h, it works !

**Comment by kerautret** [comment]
thanks @ngophuc for the report, but could you please check if it appears on current DGtal master ?

**Comment by kerautret** [comment]
It was already fix in old PR of november:
https://github.com/DGtal-team/DGtal/pull/938
