### ISSUE TITLE
[DEC] Build error of testDiscreteExteriorCalculusExtended on MacOS+clang 

### ISSUE THREAD

**Issue by dcoeurjo** [DGtal-team/DGtal#1011]
Building CXX object tests/dec/CMakeFiles/testDiscreteExteriorCalculusExtended.dir/testDiscreteExteriorCalculusExtended.cpp.o
In file included from /Users/davidcoeurjolly/Sources/DGtal/tests/dec/testDiscreteExteriorCalculusExtended.cpp:28:
/Users/davidcoeurjolly/Sources/DGtal/tests/dec/common.h:287:55: error: non-type template argument evaluates to 4294967295, which cannot be narrowed to type
      'int' [-Wc++11-narrowing]
        bool test_result = DerivativeTester<Calculus, Calculus::dimensionEmbedded-2>::test(calculus);
                                                      ^

**Comment by elcerdo** [comment]
could not reproduce on linux clang 3.6.0

**Comment by dcoeurjo** [comment]
Strange.. I do have the problem with 
   Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)

**Comment by dcoeurjo** [comment]
Fine.. fixed in #1008
