### ISSUE TITLE
qglviewer deprecated call

### ISSUE THREAD

**Issue by elcerdo** [DGtal-team/DGtal#1013]
setMouseBindingDescription(int state,...) is deprecated at least since qglviewer 2.6.1.

from qglviewer doc :
Same as calling setMouseBindingDescription(Qt::Key, Qt::KeyboardModifiers, Qt::MouseButton, QString, bool, Qt::MouseButtons), with a key value of Qt::Key(0) (i.e. binding description when no regular key needs to be pressed).

**Comment by dcoeurjo** [comment]
Fixed by @rolanddenis  
thx
