### ISSUE TITLE
line export in Board3D looks strange 

### ISSUE THREAD

**Issue by kerautret** [DGtal-team/DGtal#1025]
By testing testBoard3D and dgtalBoard3D-line.obj, it looks like that the export is strange:
<img width="791" alt="capture d ecran 2015-07-12 a 16 29 43" src="https://cloud.githubusercontent.com/assets/772865/8638227/87ec1a9e-28b4-11e5-9ad5-a142732d404e.png">

**Comment by dcoeurjo** [comment]
I agree.. it's a duplicate of  #900 I think
