### ISSUE TITLE
Problem in testEigenSolver and Eigen 3.2.0

### ISSUE THREAD

**Issue by JacquesOlivierLachaud** [DGtal-team/DGtal#1031]
The file test/math/linalg/testEigenSolver.cpp misses an include \<list\>.
Furthermore it raises a problem in Eigen with
    BOOST_CONCEPT_ASSERT(( concepts::CSparseMatrix\<Matrix, TripletsList::const_iterator\> ));

The problem has been fixed in Eigen 3.2.1:
fix: http://eigen.tuxfamily.org/index.php?title=ChangeLog#Eigen_3.2.1
bugreport: http://eigen.tuxfamily.org/bz/show_bug.cgi?id=664

We should check for Eigen 3.2.1 in DGtal.

**Comment by dcoeurjo** [comment]
closing (fixed in #1032)
