### ISSUE TITLE
Linux packages

### ISSUE THREAD

**Issue by copyme** [DGtal-team/DGtal#1062]
Instead of doing everything by hand (as page on wiki suggests) better create an account at build.opensuse.org. This service allows to automatically create, test packages and repositories for many Linux distributions eg openSUSE, Ubuntu, Debian, Arch, Fedora. You will still have to write your own spec files, etc but all other things are automatic. Personally I use for some of my own packages and it works very well.

**Comment by dcoeurjo** [comment]
Interesting.. If you have experiences on such spec files, go ahead :)

However, building a deb packages is super easy (just ˋ`ˋmake package ˋ`ˋ), the main problem is to decide which optional dependencies are considered in the binary build. Maybe several binary packages might be considered...
IMHO, but I know it is not user friendly, building form the source is much more flexible.

**Comment by dcoeurjo** [comment]
Again, that would be great if you can provide such spec thing

**Comment by copyme** [comment]
@dcoeurjo OK project is set: https://build.opensuse.org/project/show/home:copyme:DGtal

So far only DGtal, and DGtal-devel for openSUSE 13.2/1 and Fedora 22/1

DGtal is built with libQGLViewer and C11 support. 

I will add soon DGtalTools and after Ubuntu/Debian support.

Access to repos:
https://build.opensuse.org/project/repositories/home:copyme:DGtal

**Comment by copyme** [comment]
Support for x86_64: RHEL 7; Scientific Linux 7 and CentOS 7 added. These distributions have no support for QGLViewer.

**Comment by dcoeurjo** [comment]
If it is possible, please consider adding Eigen and GMP dependencies in your script. These are widely used in DEC package for instance. 
(Great job BTW)

**Comment by dcoeurjo** [comment]
Are you building the 0.9 release or the master ?

**Comment by copyme** [comment]
@dcoeurjo Eigen and GMP added. I use 0.9 release.

**Comment by copyme** [comment]
Support for ArchLinux added, but without QGLViewer.

**Comment by copyme** [comment]
Added support for QGLViewer in the ArchLinux packages.

**Comment by dcoeurjo** [comment]
Great :) 
What issues do you have with ubuntu/debian build?

**Comment by copyme** [comment]
@dcoeurjo I will try to add support for them during the next weekend.

**Comment by dcoeurjo** [comment]
:ok_hand:

**Comment by copyme** [comment]
Debian 8.0 added. I cannot provide a support for Ubuntu. Seems that universe repositories are prohibited in OBS.  Nevertheless, I think you should be able to install Debian packages in Ubuntu 15.10. Did not try because I do not have an access to any Ubuntu 15.10 machine.

**Comment by copyme** [comment]
Could you test packages and repositories? You should be able to add a repository for all supported systems. Let me know if you find any problems with this. For openSUSE you can just use software.opensuse.org and one click install mechanism.

**Comment by copyme** [comment]
Please try to add Debian repo: http://download.opensuse.org/repositories/home:/copyme:/DGtal/Debian_8.0/ and let me know if you are able to compile eg DGtalTools with.

**Comment by copyme** [comment]
Do we want all the scripts for given distributions to be kept in git?

**Comment by copyme** [comment]
A nice page where anybody can find an instruction how to configure a repository for a given system:

https://software.opensuse.org/download.html?project=home%3Acopyme%3ADGtal&package=DGtal

Debian will appear after some time.

**Comment by dcoeurjo** [comment]
Great! Is there a website where we could easily find various linux VM to tests the packages ?

**Comment by copyme** [comment]
@dcoeurjo My friend tested the installation of Debian package on Ubuntu 15.10 and it works.

**Comment by copyme** [comment]
On 14.10 also seems to work.

**Comment by dcoeurjo** [comment]
Great!!
So builds are GMP+Eigen+ (sometimes) qglviewer, am I right ?

**Comment by copyme** [comment]
Yes, you are right. If you have an access to any of supported systems (I use openSUSE 13.1 so no need to check) then you could install DGtal from packages and then try to compile DGtalTools with it. Also it will be nice if you could type ldd /usr/lib/libDGtal.so  and ldd /usr/lib/libDGtalIO.so (resp.  ldd /usr/lib64/libDGtal.so and  ldd /usr/lib64/libDGtalIO.so) and post the list here. This will help to improve dependencies. Thanks.

**Comment by copyme** [comment]
@dcoeurjo I will not have a time to write any HowTo about building packages before tomorrow. But after you will prepare the release I can create packages in 5min + building time. Moreover, I was reading about https://github.com/jordansissel/fpm seems to be an interesting tool.

**Comment by copyme** [comment]
Debian repo is here: https://software.opensuse.org/download.html?project=home%3Acopyme%3ADGtal&package=dgtal

To have all the systems in one place I need to fix a bug which concerns capital vs small letters in the name of packages.

**Comment by dcoeurjo** [comment]
The link to binary packages (except debian's) is available on the Readme.md. 

Can I close this issue ?

**Comment by copyme** [comment]
I've had some problems while building packages for 0.9.2. For this moment I have no time to take a look at this. I should know more around 17/08.
