### ISSUE TITLE
TangentFromDSS2DFunctor swap coordinates

### ISSUE THREAD

**Issue by aoblet** [DGtal-team/DGtal#1083]
You have swapped the the x and y tangent coordinates here : 
https://github.com/DGtal-team/DGtal/blob/master/src/DGtal/geometry/curves/estimation/FunctorsLambdaMST.h#L145

The formula says that "a" is deltaY and "b" is the deltaX of segment slope.

**Comment by dcoeurjo** [comment]
Thanks for the bug report. @copyme, could you please have a look to this one ?

**Comment by copyme** [comment]
@dcoeurjo I will have a look during these holidays.

**Comment by copyme** [comment]
Fixed in #1107.

**Comment by dcoeurjo** [comment]
Fixed. thanks for the bug report.
