### ISSUE TITLE
Install DGtalConfig.cmake in default lib/cmake/DGtal instead of current /share/DGtal/CMake/

### ISSUE THREAD

**Issue by phcerdan** [DGtal-team/DGtal#1095]
From: https://cmake.org/Wiki/CMake/Tutorials/Packaging
Note: If your project does not already have a <prefix>/lib/Foo*/ directory you may prefer to put the package file in <prefix>/lib/cmake/Foo*/ to keep the lib directory clean. However, CMake 2.6.2 and lower do not search there. CMake 2.6.3 and above do.

**Comment by dcoeurjo** [comment]
I agree. thanks for the report.
