### ISSUE TITLE
Possible bug in Hull2DHelpers ```compute*Distance```

### ISSUE THREAD

**Issue by dcoeurjo** [DGtal-team/DGtal#1098]
To remove some warnings, I have changed the (Hull2DHelpers.ih, lines 440,459..)

           double k = -(a[0]-b[0])*c[1]-(b[0]*a[1]-a[0]*b[1]);
           TInputPoint p (k/(b[1]-a[1]), c[1]);

to 

           auto k = -(a[0]-b[0])*c[1]-(b[0]*a[1]-a[0]*b[1]);
           TInputPoint p (k/(b[1]-a[1]), c[1]);

In order to avoid an implicit cast double->int while computing the point ```p``` (assuming that the Coordinate type of TInputPoint is integer)

By doing so, the unit test ```testAlphaThickSegmentComputer```now fails.

@kerautret Can you please have a look to all "compute**distances" functions to check the arithmetic ? 
(For instance in ```computeEuclideanDistance```, it is dangerous to perform a sign test in ```doubles``` when it is not needed).

**Comment by kerautret** [comment]
@dcoeurjo ok I look it on your branch MSBuild.

**Comment by dcoeurjo** [comment]
I have reverted it in my branch.

**Comment by kerautret** [comment]
@dcoeurjo done, I apply a PR on your branch :)

**Comment by dcoeurjo** [comment]
fixed. thanks.
