### ISSUE TITLE
Compliation of testLocalConvolutionNormalVectorEstimator.cpp failed

### ISSUE THREAD

**Issue by copyme** [DGtal-team/DGtal#1114]
While compiling with clang version 3.3 I got the following errors:

[ 57%] Building CXX object tests/geometry/surfaces/CMakeFiles/testLocalConvolutionNormalVectorEstimator.dir/testLocalConvolutionNormalVectorEstimator.cpp.o
In file included from /home/kacper/projects/DGtal/tests/geometry/surfaces/testLocalConvolutionNormalVectorEstimator.cpp:49:
In file included from /home/kacper/projects/DGtal/src/DGtal/io/viewers/Viewer3D.h:1374:
In file included from /home/kacper/projects/DGtal/src/DGtal/io/viewers/Viewer3D.ih:54:
In file included from /home/kacper/projects/DGtal/src/DGtal/io/viewers/Viewer3DFactory.h:48:
/home/kacper/projects/DGtal/src/DGtal/io/viewers/DrawWithViewer3DModifier.h:262:55: error: expected ')'
                                 Viewer3D<Space,KSpace>::GrayScaleMode): my2DImage(&anImage),
                                                      ^
/home/kacper/projects/DGtal/src/DGtal/io/viewers/DrawWithViewer3DModifier.h:259:33: note: to match this '('
    AddTextureImage2DWithFunctor(ConstAlias<TImageType> anImage,
                                ^
/home/kacper/projects/DGtal/src/DGtal/io/viewers/DrawWithViewer3DModifier.h:262:48: error: expected '>'
                                 Viewer3D<Space,KSpace>::GrayScaleMode): my2DImage(&anImage),
                                               ^
/home/kacper/projects/DGtal/src/DGtal/io/viewers/DrawWithViewer3DModifier.h:308:108: error: expected ')'
                                 typename Viewer3D<Space,KSpace>::TextureMode aMode = Viewer3D<Space,KSpace>::GrayScaleMode): my3DImage(&anImage),
                                                                                                           ^
/home/kacper/projects/DGtal/src/DGtal/io/viewers/DrawWithViewer3DModifier.h:306:33: note: to match this '('
    AddTextureImage3DWithFunctor(ConstAlias<TImageType> anImage,
                                ^
/home/kacper/projects/DGtal/src/DGtal/io/viewers/DrawWithViewer3DModifier.h:308:101: error: expected '>'
                                 typename Viewer3D<Space,KSpace>::TextureMode aMode = Viewer3D<Space,KSpace>::GrayScaleMode): my3DImage(&anImage),
                                                                                                    ^
4 errors generated.
make[2]: *** [tests/geometry/surfaces/CMakeFiles/testLocalConvolutionNormalVectorEstimator.dir/testLocalConvolutionNormalVectorEstimator.cpp.o] Error 1
make[1]: *** [tests/geometry/surfaces/CMakeFiles/testLocalConvolutionNormalVectorEstimator.dir/all] Error 2
make: *** [all] Error 2

**Comment by kerautret** [comment]
are you sure to have the last current master version ? (some edits were given 8 days ago)

**Comment by copyme** [comment]
@kerautret yes

kacper@kasia:~/projects/DGtal> git pull upstream master
From https://github.com/DGtal-team/DGtal
 * branch            master     -> FETCH_HEAD
Already up-to-date.

**Comment by kerautret** [comment]
strange, I have no errors on clang 3.0...
( clang version 3.0-6.2 (tags/RELEASE_30/final) (based on LLVM 3.0))

**Comment by kerautret** [comment]
thanks for the issue, could you please test if my branch TestFixIssue114 solve you issue ?
(https://github.com/kerautret/DGtal/tree/TestFixIssue114)

**Comment by copyme** [comment]
@kerautret It works right now. Thanks for your fix.

**Comment by kerautret** [comment]
ok thanks @copyme for the feed back I put a PR ;)
