### ISSUE TITLE
Enable CGAL and Eigen in Travis/Appeveyor bots

### ISSUE THREAD

**Issue by dcoeurjo** [DGtal-team/DGtal#1136]

**Comment by kerautret** [comment]
for appveyor I think that it should be difficult due to the timeout (we have few minutes left for the timeout and sometime it is over)

**Comment by dcoeurjo** [comment]
Seems to be ok for Eigen.

**Comment by dcoeurjo** [comment]
For cGAL, I think they have a "header only" mode that could help the build on windows

**Comment by kerautret** [comment]
@dcoeurjo actually I tried to use CGAL to make run again the 3dLocalEstimators but impossible to do it on my computer, I tried different config using brew, of from CGAL source and always the same message:
` The requested CGAL component Eigen3 does not exist!`
While it is well found with by DGtal.

**Comment by kerautret** [comment]
Did the @DGtal-team/package-managers have the same issue ?

**Comment by dcoeurjo** [comment]
When using monge/Jetfitting estimator from CGAL,  CGAL must have been compiled with the Eigen3 option.

**Comment by dcoeurjo** [comment]
for instance, I don't know if CGAL ubuntu packages is shipped with the Eigen option.

**Comment by kerautret** [comment]
ok I see I try

**Comment by kerautret** [comment]
thanks

**Comment by kerautret** [comment]
I had it by compiling CGAL with Eigen option.
> For cGAL, I think they have a "header only" mode that could help the build on windows

it looks like it will no help :( 
But it could be useful since I get several errors in 3dLocalEstimators.cpp

**Comment by rolanddenis** [comment]
I have the same issue (self-compiled CGAL with available Eigen3). By looking at the cmake scripts, it seems that Eigen3 is not seen as a component anymore since version 4.12 of CGAL. It is maybe related to the header-only mode of CGAL and the detected of Eigen3 is delayed at the final compilation (e.g. DGtal or DGtalTools).
