### ISSUE TITLE
examples/geometry/curves/exampleArithDSSIterator does not compile...

### ISSUE THREAD

**Issue by kerautret** [DGtal-team/DGtal#1165]
The example exampleArithDSSIterator does not compile and is not in the CMakeList:
In file included from /Users/kerautre/EnCours/DGtal/examples/geometry/curves/exampleArithDSSIterator.cpp:32:
In file included from /Users/kerautre/EnCours/DGtal/src/DGtal/base/Common.h:59:
/usr/local/include/boost/iterator/iterator_concepts.hpp:125:18: error: cannot increment value of type
      'DGtal::ArithDSSIterator<int, 8>'
          (void)i++;
                ~^
/usr/local/include/boost/concept/usage.hpp:16:43: note: in instantiation of member function
      'boost_concepts::IncrementableIterator<DGtal::ArithDSSIterator<int, 8> >::~IncrementableIterator' requested here
    ~usage_requirements() { ((Model_)0)->~Model(); }
                                          ^
/usr/local/include/boost/concept/detail/general.hpp:39:42: note: in instantiation of member function
      'boost::concepts::usage_requirements<boost_concepts::IncrementableIterator<DGtal::ArithDSSIterator<int, 8> >
      >::~usage_requirements' requested here
    static void failed() { ((Model_)0)->~Model(); }
                                         ^
/usr/local/include/boost/iterator/iterator_concepts.hpp:122:7: note: in instantiation of member function
      'boost::concepts::requirement<boost::concepts::failed
      ************boost::concepts::usage_requirements<boost_concepts::IncrementableIterator<DGtal::ArithDSSIterator<int, 8> >
      >::***********_>::failed' requested here
      BOOST_CONCEPT_USAGE(IncrementableIterator)
      ^
/usr/local/include/boost/concept/usage.hpp:29:7: note: expanded from macro 'BOOST_CONCEPT_USAGE'
      BOOST_CONCEPT_ASSERT((boost::concepts::usage_requirements<model>)); \
      ^
/usr/local/include/boost/concept/assert.hpp:43:5: note: expanded from macro 'BOOST_CONCEPT_ASSERT'
    BOOST_CONCEPT_ASSERT_FN(void(_)ModelInParens)
    ^
/usr/local/include/boost/concept/detail/general.hpp:71:51: note: expanded from macro 'BOOST_CONCEPT_ASSERT_FN'
    &::boost::concepts::requirement_<ModelFnPtr>::failed>    \
                                                  ^
1 error generated.
make[3]: **\* [examples/geometry/curves/CMakeFiles/exampleArithDSSIterator.dir/exampleArithDSSIterator.cpp.o] Error 1
make[2]: **\* [examples/geometry/curves/CMakeFiles/exampleArithDSSIterator.dir/all] Error 2
make[1]: **\* [examples/geometry/curves/CMakeFiles/exampleArithDSSIterator.dir/rule] Error 2
make: **\* [exampleArithDSSIterator] Error 2

**Comment by dcoeurjo** [comment]
@kerautret can you please have a look to @isivigno 's PR #1187 ?
Does it fix this bug?

**Comment by kerautret** [comment]
@dcoeurjo  @isivigno yes that works ;)! thanks ;)

**Comment by isivigno** [comment]
I think this issue was closed by PR #1187 ? Is that right ?

**Comment by dcoeurjo** [comment]
yep :) 
Thanks, closing
