### ISSUE TITLE
Move @example doxygen section to the example files.

### ISSUE THREAD

**Issue by dcoeurjo** [DGtal-team/DGtal#1191]
See #1166, we should move all @example doxygen section to the associated example CPP file (similarly to DGtalTools).

**Comment by kerautret** [comment]
I look it this week end

**Comment by kerautret** [comment]
@dcoeurjo is it ok for you such move: 
https://github.com/kerautret/DGtal/commit/7afac571f7f03187153f68f8363804fb3cbbfb5c

**Comment by dcoeurjo** [comment]
thanks @kerautret . Fixed in 0.9.3
