### ISSUE TITLE
Compilation Error with boost  1.49.0

### ISSUE THREAD

**Issue by kerautret** [DGtal-team/DGtal#1201]
In the examples (and tests) various errors related to boost.
(gcc (Debian 4.9.2-10) 4.9.2)
------

[100%] Building CXX object examples/graph/CMakeFiles/graphTraversal.dir/graphTraversal.cpp.o
In file included from /home/kerautre/DGtal/src/DGtal/kernel/CInteger.h:49:0,
                 from /home/kerautre/DGtal/src/DGtal/arithmetic/ModuloComputer.h:46,
                 from /home/kerautre/DGtal/src/DGtal/math/AngleLinearMinimizer.h:51,
                 from /home/kerautre/DGtal/src/DGtal/io/Display2DFactory.h:50,
                 from /home/kerautre/DGtal/src/DGtal/io/boards/Board2D.h:428,
                 from /home/kerautre/DGtal/examples/graph/graphTraversal.cpp:23:
/home/kerautre/DGtal/src/DGtal/kernel/CIntegralNumber.h: In instantiation of ‘DGtal::concepts::CIntegralNumber<T>::~CIntegralNumber() [with T = long unsigned int]’:
/usr/include/boost/concept/detail/general.hpp:38:28:   required from ‘static void boost::concepts::requirement<boost::concepts::failed************ Model::************>::failed() [with Model = DGtal::concepts::CIntegralNumber<long unsigned int>]’
/home/kerautre/DGtal/src/DGtal/kernel/CSpace.h:121:5:   required from ‘struct DGtal::concepts::CUndirectedSimpleLocalGraph<DGtal::Object<DGtal::DigitalTopology<DGtal::MetricAdjacency<DGtal::SpaceND<2u, int>, 1u>, DGtal::MetricAdjacency<DGtal::SpaceND<2u, int>, 2u> >, DGtal::DigitalSetByAssociativeContainer<DGtal::HyperRectDomain<DGtal::SpaceND<2u, int> >, std::unordered_set<DGtal::PointVector<2u, int, std::array<int, 2ul> >, std::hash<DGtal::PointVector<2u, int, std::array<int, 2ul> > >, std::equal_to<DGtal::PointVector<2u, int, std::array<int, 2ul> > >, std::allocator<DGtal::PointVector<2u, int, std::array<int, 2ul> > > > > > >’
/home/kerautre/DGtal/src/DGtal/graph/CUndirectedSimpleGraph.h:102:10:   required from ‘struct DGtal::concepts::CUndirectedSimpleGraph<DGtal::Object<DGtal::DigitalTopology<DGtal::MetricAdjacency<DGtal::SpaceND<2u, int>, 1u>, DGtal::MetricAdjacency<DGtal::SpaceND<2u, int>, 2u> >, DGtal::DigitalSetByAssociativeContainer<DGtal::HyperRectDomain<DGtal::SpaceND<2u, int> >, std::unordered_set<DGtal::PointVector<2u, int, std::array<int, 2ul> >, std::hash<DGtal::PointVector<2u, int, std::array<int, 2ul> > >, std::equal_to<DGtal::PointVector<2u, int, std::array<int, 2ul> > >, std::allocator<DGtal::PointVector<2u, int, std::array<int, 2ul> > > > > > >’
/usr/include/boost/concept/detail/has_constraints.hpp:32:62:   required by substitution of ‘template<class Model> boost::concepts::detail::yes boost::concepts::detail::has_constraints_(Model*, boost::concepts::detail::wrap_constraints<Model, (& Model:: constraints)>*) [with Model = DGtal::concepts::CUndirectedSimpleGraph<DGtal::Object<DGtal::DigitalTopology<DGtal::MetricAdjacency<DGtal::SpaceND<2u, int>, 1u>, DGtal::MetricAdjacency<DGtal::SpaceND<2u, int>, 2u> >, DGtal::DigitalSetByAssociativeContainer<DGtal::HyperRectDomain<DGtal::SpaceND<2u, int> >, std::unordered_set<DGtal::PointVector<2u, int, std::array<int, 2ul> >, std::hash<DGtal::PointVector<2u, int, std::array<int, 2ul> > >, std::equal_to<DGtal::PointVector<2u, int, std::array<int, 2ul> > >, std::allocator<DGtal::PointVector<2u, int, std::array<int, 2ul> > > > > > >]’
/usr/include/boost/concept/detail/has_constraints.hpp:42:5:   required from ‘const bool boost::concepts::not_satisfied<DGtal::concepts::CUndirectedSimpleGraph<DGtal::Object<DGtal::DigitalTopology<DGtal::MetricAdjacency<DGtal::SpaceND<2u, int>, 1u>, DGtal::MetricAdjacency<DGtal::SpaceND<2u, int>, 2u> >, DGtal::DigitalSetByAssociativeContainer<DGtal::HyperRectDomain<DGtal::SpaceND<2u, int> >, std::unordered_set<DGtal::PointVector<2u, int, std::array<int, 2ul> >, std::hash<DGtal::PointVector<2u, int, std::array<int, 2ul> > >, std::equal_to<DGtal::PointVector<2u, int, std::array<int, 2ul> > >, std::allocator<DGtal::PointVector<2u, int, std::array<int, 2ul> > > > > > > >::value’
/usr/include/boost/concept/detail/has_constraints.hpp:45:31:   required from ‘struct boost::concepts::not_satisfied<DGtal::concepts::CUndirectedSimpleGraph<DGtal::Object<DGtal::DigitalTopology<DGtal::MetricAdjacency<DGtal::SpaceND<2u, int>, 1u>, DGtal::MetricAdjacency<DGtal::SpaceND<2u, int>, 2u> >, DGtal::DigitalSetByAssociativeContainer<DGtal::HyperRectDomain<DGtal::SpaceND<2u, int> >, std::unordered_set<DGtal::PointVector<2u, int, std::array<int, 2ul> >, std::hash<DGtal::PointVector<2u, int, std::array<int, 2ul> > >, std::equal_to<DGtal::PointVector<2u, int, std::array<int, 2ul> > >, std::allocator<DGtal::PointVector<2u, int, std::array<int, 2ul> > > > > > > >’
/usr/include/boost/mpl/if.hpp:67:11:   required from ‘struct boost::mpl::if_<boost::concepts::not_satisfied<DGtal::concepts::CUndirectedSimpleGraph<DGtal::Object<DGtal::DigitalTopology<DGtal::MetricAdjacency<DGtal::SpaceND<2u, int>, 1u>, DGtal::MetricAdjacency<DGtal::SpaceND<2u, int>, 2u> >, DGtal::DigitalSetByAssociativeContainer<DGtal::HyperRectDomain<DGtal::SpaceND<2u, int> >, std::unordered_set<DGtal::PointVector<2u, int, std::array<int, 2ul> >, std::hash<DGtal::PointVector<2u, int, std::array<int, 2ul> > >, std::equal_to<DGtal::PointVector<2u, int, std::array<int, 2ul> > >, std::allocator<DGtal::PointVector<2u, int, std::array<int, 2ul> > > > > > > >, boost::concepts::constraint<DGtal::concepts::CUndirectedSimpleGraph<DGtal::Object<DGtal::DigitalTopology<DGtal::MetricAdjacency<DGtal::SpaceND<2u, int>, 1u>, DGtal::MetricAdjacency<DGtal::SpaceND<2u, int>, 2u> >, DGtal::DigitalSetByAssociativeContainer<DGtal::HyperRectDomain<DGtal::SpaceND<2u, int> >, std::unordered_set<DGtal::PointVector<2u, int, std::array<int, 2ul> >, std::hash<DGtal::PointVector<2u, int, std::array<int, 2ul> > >, std::equal_to<DGtal::PointVector<2u, int, std::array<int, 2ul> > >, std::allocator<DGtal::PointVector<2u, int, std::array<int, 2ul> > > > > > > >, boost::concepts::requirement<boost::concepts::failed************ DGtal::concepts::CUndirectedSimpleGraph<DGtal::Object<DGtal::DigitalTopology<DGtal::MetricAdjacency<DGtal::SpaceND<2u, int>, 1u>, DGtal::MetricAdjacency<DGtal::SpaceND<2u, int>, 2u> >, DGtal::DigitalSetByAssociativeContainer<DGtal::HyperRectDomain<DGtal::SpaceND<2u, int> >, std::unordered_set<DGtal::PointVector<2u, int, std::array<int, 2ul> >, std::hash<DGtal::PointVector<2u, int, std::array<int, 2ul> > >, std::equal_to<DGtal::PointVector<2u, int, std::array<int, 2ul> > >, std::allocator<DGtal::PointVector<2u, int, std::array<int, 2ul> > > > > > >::************> >’
/usr/include/boost/concept/detail/general.hpp:50:8:   required from ‘struct boost::concepts::requirement_<void (*)(DGtal::concepts::CUndirectedSimpleGraph<DGtal::Object<DGtal::DigitalTopology<DGtal::MetricAdjacency<DGtal::SpaceND<2u, int>, 1u>, DGtal::MetricAdjacency<DGtal::SpaceND<2u, int>, 2u> >, DGtal::DigitalSetByAssociativeContainer<DGtal::HyperRectDomain<DGtal::SpaceND<2u, int> >, std::unordered_set<DGtal::PointVector<2u, int, std::array<int, 2ul> >, std::hash<DGtal::PointVector<2u, int, std::array<int, 2ul> > >, std::equal_to<DGtal::PointVector<2u, int, std::array<int, 2ul> > >, std::allocator<DGtal::PointVector<2u, int, std::array<int, 2ul> > > > > > >)>’
/home/kerautre/DGtal/examples/graph/graphTraversal.cpp:55:3:   required from here
/home/kerautre/DGtal/src/DGtal/kernel/CIntegralNumber.h:108:45: error: invalid initialization of reference of type ‘const DGtal::TagTrue&’ from expression of type ‘DGtal::NumberTraits<long unsigned int>::IsIntegral {aka DGtal::TagUnknown}’
       ConceptUtils::checkTrue( myIsIntegral );
                                             ^
In file included from /home/kerautre/DGtal/src/DGtal/base/Common.h:97:0,
                 from /home/kerautre/DGtal/src/DGtal/io/Color.h:45,
                 from /home/kerautre/DGtal/examples/graph/graphTraversal.cpp:20:
/home/kerautre/DGtal/src/DGtal/base/ConceptUtils.h:167:8: note: in passing argument 1 of ‘void DGtal::concepts::ConceptUtils::checkTrue(const DGtal::TagTrue&)’
   void checkTrue( const TagTrue & tag );
        ^
examples/graph/CMakeFiles/graphTraversal.dir/build.make:54: recipe for target 'examples/graph/CMakeFiles/graphTraversal.dir/graphTraversal.cpp.o' failed
make[2]: *** [examples/graph/CMakeFiles/graphTraversal.dir/graphTraversal.cpp.o] Error 1
CMakeFiles/Makefile2:3952: recipe for target 'examples/graph/CMakeFiles/graphTraversal.dir/all' failed
make[1]: *** [examples/graph/CMakeFiles/graphTraversal.dir/all] Error 2
Makefile:133: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by kerautret** [comment]
I wonder If we have not interest to include one version of boost in DGtal ? (it looks a recurrent error source)

**Comment by kerautret** [comment]
I confirm no more pb using boost 1.55.0

**Comment by dcoeurjo** [comment]
I think that it is specific to version 1.49 of boost. I remember having similar issue as well..

**Comment by dcoeurjo** [comment]
can I close this issue ?

**Comment by kerautret** [comment]
I check it...

**Comment by kerautret** [comment]
Yes I confirm it compile now also with boost 1.49 ;)
it was a fix of @rolanddenis if I well remember thanks by the way ! ;)
