### ISSUE TITLE
Problem with Linux packages of 0.9.2

### ISSUE THREAD

**Issue by copyme** [DGtal-team/DGtal#1207]
While running the scripts there is: 

CMake Error: Could not open file for write in copy operation /usr/include/DGtal/topology/tables/NeighborhoodTables.h.tmp

The problem is that a building script should not try to create anything in /usr

So far I've had no luck to track down this problem.

**Comment by dcoeurjo** [comment]
From the script, what is your  ```PROJECT_BINARY_DIR``` ?

**Comment by copyme** [comment]
It seems to be correct: /home/kacper/rpmbuild/BUILD/DGtal-0.9.2/build

**Comment by copyme** [comment]
Moved to #1229
