### ISSUE TITLE
cmake Qt5 discovery on macos

### ISSUE THREAD

**Issue by dcoeurjo** [DGtal-team/DGtal#1210]
When compiling DGtal with Qt/Qt5 (5.7.0) with cmake (3.6.2), cmake complains about a missing FindQt5.cmake script (or any config file that loads Qt5 settings).

@kerautret can you reproduce this issue ?

````
CMake Error at cmake/CheckDGtalOptionalDependencies.cmake:297 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:40 (INCLUDE)
`````

**Comment by dcoeurjo** [comment]
ping @kerautret

**Comment by kerautret** [comment]
Yes I also have it... but it is because I have a custom dir of QT5 installation so I set it manually ...

**Comment by dcoeurjo** [comment]
Can you confirm that there is no FindQT5 in cmake (or custom script) ?

**Comment by kerautret** [comment]
yes since QT5 provide a Qt5Config.cmake :
https://github.com/Cockatrice/Cockatrice/issues/205

**Comment by dcoeurjo** [comment]
ok I see..

**Comment by dcoeurjo** [comment]
You would have to set the `Qt5_DIR` or `CMAKE_PREFIX_PATH` variable during the cmake step.  

On macOS using home-brew package manager, I use the following shortcut:  

      cmake .. -DCMAKE_PREFIX_PATH=$(brew --prefix qt5)

**Comment by GD-B-150793** [comment]
thank you for helping i need another help

-- The following ICU libraries were not found:

--   i18n (required)

--   uc (required)

CMake Error at
/usr/local/Cellar/cmake/3.12.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137
(message):

  Failed to find all ICU components (missing: ICU_INCLUDE_DIR ICU_LIBRARY

  _ICU_REQUIRED_LIBS_FOUND)


i am getting this error can you tell me how to solve

**Comment by dcoeurjo** [comment]
I've no idea where these issues come from but it is not related to DGtal.
Check your Qt installs (if the ICU is loaded when activating this deps) but there is nothing we can do on our side

**Comment by GD-B-150793** [comment]
i am doing my final year project on ontalogy based authoring tool....for
which i am trying to download miktex source code and then build it so i can
change the source code to according our FYP
for which i downloaded source code from github then they show me the link
where i get the step to build on mac
where i stuck on this line of code
cmake ../miktex-master

on which i get this error

INFOfribidi libs: /usr/local/Cellar/fribidi/1.0.5/lib/libfribidi.dylib

INFOfribidi incs:
/usr/local/Cellar/fribidi/1.0.5/include/fribidi;/usr/local/Cellar/fribidi/1.0.5/include

-- The following ICU libraries were not found:

--   i18n (required)

--   uc (required)

CMake Error at
/usr/local/Cellar/cmake/3.12.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137
(message):

  Failed to find all ICU components (missing: ICU_INCLUDE_DIR ICU_LIBRARY

  _ICU_REQUIRED_LIBS_FOUND)

Call Stack (most recent call first):

  /usr/local/Cellar/cmake/3.12.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378
(_FPHSA_FAILURE_MESSAGE)

  /usr/local/Cellar/cmake/3.12.2/share/cmake/Modules/FindICU.cmake:317
(FIND_PACKAGE_HANDLE_STANDARD_ARGS)

  CMakeLists.txt:1032 (find_package)



-- Configuring incomplete, errors occurred!

See also "/Users/afnisaeed/Desktop/CMakeFiles/CMakeOutput.log".

**Comment by dcoeurjo** [comment]
Does it have to do with DGtal ?

**Comment by GD-B-150793** [comment]
NO
https://miktex.org/howto/build-mac
this is the link

**Comment by dcoeurjo** [comment]
So report the issue to miktex developers

**Comment by GD-B-150793** [comment]
can you suggest me any developer

**Comment by GD-B-150793** [comment]
i have to do my fyp please help me

**Comment by dcoeurjo** [comment]
google miktex, DGtal project has no relationship with them.
