### ISSUE TITLE
Dec test:  testLinearStructure fails on linux (eigen 3.2)

### ISSUE THREAD

**Issue by kerautret** [DGtal-team/DGtal#1212]
By testing to add Eigen in travis the testLinearStructure fails (with clang):
https://travis-ci.org/kerautret/DGtal/jobs/169803599
It is strange because it works fine on my mac...

**Comment by JacquesOlivierLachaud** [comment]
It looks like the order of cells has changed or is not the one expected (when looking at the linear operator matrix values). @elcerdo have you changed the way cells are indexed ?

**Comment by dcoeurjo** [comment]
Now travis checks Eigen/DEC in #1214 and raises the issue.

ping @elcerdo

**Comment by elcerdo** [comment]
The new ordering of cells has been compensated for in #1020 .
As observed by @kerautret, everything seams fine on my machine.

**Comment by dcoeurjo** [comment]
should be ok now
