### ISSUE TITLE
Issue with DGtalConfig.cmake

### ISSUE THREAD

**Issue by Laefy** [DGtal-team/DGtal#1219]
Using FIND_PACKAGE(DGtal) sets -std=c++11, without warning the user.
He cannot for example ask for -std=c++14 before using FIND_PACKAGE, as it will be "overridden" by calling FIND_PACKAGE.

**Comment by dcoeurjo** [comment]
Dear @Laefy

I agree DGtalConfig forces the cpp11 compiler flags (and may discard previous manually set settings). 

Maybe we should first test if the compiler is cpp11 compliant without any flag (or with prior user specified flag) before setting the required c++11...

Thanks for the report.

**Comment by phcerdan** [comment]
+1 for checking flags before forcing c++11.
It does not work well when the compiler default is c++14.

I am hitting this bug with gcc (6.2.1)+boost (1.62): https://svn.boost.org/trac/boost/ticket/9240.
It might be triggered when setting user defined compilation flags (std=c++11) as pointed here.
http://www.boost.org/doc/libs/1_61_0/libs/math/doc/html/math_toolkit/float128.html
And also warnings about different compilation flags if I link a tool to DGtal with the default (>c++11) flag.

**Comment by dcoeurjo** [comment]
Fixed now in #1222 
Thanks @Laefy for the report.

**Comment by Laefy** [comment]
Thanks to you for fixing :)
