### ISSUE TITLE
SternBrocot: description in Latex math mode

### ISSUE THREAD

**Issue by copyme** [DGtal-team/DGtal#1223]
In the documentation of **Fraction DGtal::SternBrocot< TInteger, TQuotient >::Fraction::simplestFractionInBetween 	( 	const Fraction &  	other	) 	const** (http://dgtal.org/doc/stable/classDGtal_1_1SternBrocot_1_1Fraction.html) the description of complexity is in the math mode so spaces were removed. "a fraction NB: O(k)wherekisthedepthoftheoutputfraction."

**Comment by isivigno** [comment]
Thank you ! see pull request #1224 for the correction.

**Comment by dcoeurjo** [comment]
closing since fixed in #1224
