### ISSUE TITLE
DGtalIO library is not added in the build tree.

### ISSUE THREAD

**Issue by phcerdan** [DGtal-team/DGtal#1225]
I am facing `-lDGtalIO` not found when linking to the build tree in an application.
If I link to the install tree there is no problem.
It triggers from the line [DGtalConfig.cmake.in#L179](https://github.com/DGtal-team/DGtal/blob/master/cmake/DGtalConfig.cmake.in#L179)
The generated DGtalLibraryDepends.cmake in the build tree doesn't `add_library(DGtalIO)` but it does in the same file in the install tree.
Check this [gist](https://gist.github.com/phcerdan/f1b8943ad77b1b958603391e734804ab) for comparison .

Maybe it is because it only exports `DGtalIO` when `WITH_VISU3D` is defined?
[DGtalConfigGenerator.cmake#L5](https://github.com/DGtal-team/DGtal/blob/master/cmake/DGtalConfigGenerator.cmake#L5)

`cmake --version => 3.6.3`

**Comment by dcoeurjo** [comment]
Yes you're absolutely right. The test at DGtalConfigGenerator.cmake#L5 should be removed (there are classes compiled in DGtalIO that are not related to ```WITH_VISU_3D```).

The split decision between DGtal and DGtalIO is quite old now.. Maybe we should clarify everything by just removing the DGtalIO target and compile everything into the main DGtal lib.

@JacquesOlivierLachaud, what do you think ?

**Comment by JacquesOlivierLachaud** [comment]
I suggest to remove the DGtalIO, and to have only one libDGtal, the split being old and unclear. So I do agree !

**Comment by phcerdan** [comment]
Thanks!
