### ISSUE TITLE
DGtal doc Header  missing in examples/dec files

### ISSUE THREAD

**Issue by kerautret** [DGtal-team/DGtal#1239]

**Comment by dcoeurjo** [comment]
?? which one ?

**Comment by kerautret** [comment]
all: exampleDECSurface.cpp, exampleDiscreteExteriorCalculusChladni.cpp, exampleDiscreteExteriorCalculusSolve.cpp, exampleDiscreteExteriorCalculusUsage.cpp examplePropagation.cpp
(just the licence and other header info)

**Comment by dcoeurjo** [comment]
what do you mean by "DGtal doc Header" ?

**Comment by dcoeurjo** [comment]
ah ok, the doxygen documentation and the LGPL license ?

**Comment by kerautret** [comment]
yes
