### ISSUE TITLE
testBasicPointFunctors fails 

### ISSUE THREAD

**Issue by dcoeurjo** [DGtal-team/DGtal#1243]
@kerautret this test has been disabled in the cmakelist and I don't remember why (still failing). Can you please have a look ?

(cf tests/kernel/CMakeLists.txt l:12-13)

thx

**Comment by kerautret** [comment]
I see, I miss it thanks, I PR a fix

**Comment by kerautret** [comment]
should be fix in PR  #1245

**Comment by dcoeurjo** [comment]
seems to be fixed. closing
