### ISSUE TITLE
Bugs in melkmanConvexHullAlgorithm

### ISSUE THREAD

**Issue by ngophuc** [DGtal-team/DGtal#1251]
I tried DGtal::functions::Hull2D::melkmanConvexHullAlgorithm on the sequence of points in the attached file and I dont obtain a good result (see attachement as well).
[tmpAshape_1.txt](https://github.com/DGtal-team/DGtal/files/838841/tmpAshape_1.txt)
![res](https://cloud.githubusercontent.com/assets/10596287/23864037/9ff1e676-0811-11e7-9b4f-ad6b5298a334.png)

**Comment by dcoeurjo** [comment]
dear @ngophuc , what was the problem ?

**Comment by ngophuc** [comment]
It's solved. In fact, I was my fault, I did not read the doc carefully.
