### ISSUE TITLE
Nightly build doxygen documentation not updated

### ISSUE THREAD

**Issue by rolanddenis** [DGtal-team/DGtal#1267]
The nightly build of the documentation was lastly generated at November 7th (see http://dgtal.org/doc/nightly/index.html ).

**Comment by dcoeurjo** [comment]
;)
I use rsync to push the doc and it transfers file only when they have changed..

**Comment by dcoeurjo** [comment]
Agree... the issue is indeed important

**Comment by rolanddenis** [comment]
What's up doc ? :popcorn:

**Comment by dcoeurjo** [comment]
;)
There is a problem with the ssh key I use to push the doc the the liris server without asking a password...

**Comment by dcoeurjo** [comment]
Still W.I.P

**Comment by rolanddenis** [comment]
I see... good luck !

**Comment by rolanddenis** [comment]
But is it not the same key as the one used for the release documentation ?

**Comment by dcoeurjo** [comment]
The key is the same but within Travis, the process is slighlty different (keys must be encrypted) and I need to double check the config

**Comment by dcoeurjo** [comment]
looks like it's fine now ;)

**Comment by dcoeurjo** [comment]
closing this issue

**Comment by rolanddenis** [comment]
Nice, thanks !
