### ISSUE TITLE
Incorrect links to the Linux packages in README.md

### ISSUE THREAD

**Issue by copyme** [DGtal-team/DGtal#1277]
The correct links are:

Debian/Ubuntu: http://software.opensuse.org//download.html?project=home%3Acopyme%3ADGtal&package=dgtal

All the rest: http://software.opensuse.org//download.html?project=home%3Acopyme%3ADGtal&package=libDGtal

**Comment by dcoeurjo** [comment]
thanks for the report. Can you please create a PR editing the README ?

**Comment by copyme** [comment]
@dcoeurjo done

**Comment by dcoeurjo** [comment]
Thx

**Comment by dcoeurjo** [comment]
merged, thank you
