### ISSUE TITLE
Update CMake version requirement and avoid setting CXX_CMAKE_FLAGS

### ISSUE THREAD

**Issue by phcerdan** [DGtal-team/DGtal#1283]
`cmake 3.1` added the `CXX_STANDARD_REQUIRED`. Check [more about this in SO.](https://stackoverflow.com/questions/37621342/cmake-will-not-compile-to-c-11-standard)

Not a good practice to hardcode `CXX_CMAKE_FLAGS` with recent `cmake`.
I have found these recommendations from Daniel Pfeifer quite helpful [video](https://www.youtube.com/watch?v=bsXLMQ6WgIk), [slides](https://github.com/boostcon/cppnow_presentations_2017/blob/master/05-19-2017_friday/effective_cmake__daniel_pfeifer__cppnow_05-19-2017.pdf)

**Comment by dcoeurjo** [comment]
So you're suggesting this, right ?

    set(CMAKE_CXX_STANDARD 11) # C++11...
    set(CMAKE_CXX_STANDARD_REQUIRED ON) #...is required...
    set(CMAKE_CXX_EXTENSIONS OFF) #...without compiler extensions like gnu++11

**Comment by phcerdan** [comment]
Yes, also: `cmake_minimum_required(VERSION 3.1)` for that to work.

**Comment by phcerdan** [comment]
Reference to other source codes transition: https://github.com/open-source-parsers/jsoncpp/issues/548

**Comment by dcoeurjo** [comment]
something like that  #1290 ?

**Comment by phcerdan** [comment]
Closing via #1290, thanks @dcoeurjo!
