### ISSUE TITLE
[deprecated] dynamic_exception

### ISSUE THREAD

**Issue by phcerdan** [DGtal-team/DGtal#1284]
Many warnings when compiling with gcc 7.2:
```
/src/DGtal/geometry/curves/FP.ih:45:27: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
    const TIterator& ite ) throw( InputException )
```

**Comment by rolanddenis** [comment]
Yep, we should instead use `noexcept` to specify functions that don't throw. I think that we can first remove all `throw`specifications ... I'm on it unless you or @dcoeurjo are already fixing this ?

**Comment by dcoeurjo** [comment]
go ahead;)

**Comment by rolanddenis** [comment]
In progress in #1285. @phcerdan, do you still have warnings ?

**Comment by phcerdan** [comment]
Closing via #1285 , thanks @rolanddenis!
