### ISSUE TITLE
[deprecated] std::unary_function, std::binary_function

### ISSUE THREAD

**Issue by phcerdan** [DGtal-team/DGtal#1288]
The standard deprecated these in c++11, and might cause compile errors in c++17. This is in the same line than `binder1st`, `binder2nd` (they favour the  usage of std::bind, std::function, decltype, result_of).

There are a few libraries hit by these. Check conversation about this in boost for solutions: http://boost.2283326.n4.nabble.com/What-to-do-about-std-binary-function-and-std-unary-function-td4685873.html.

Maybe solution 4 seems the cleanest (remove typedefs), but haven't checked if these typedefs defined by `std::unary_function` are used elsewhere in DGtal.

Related #1221 , #1287

**Comment by phcerdan** [comment]
DGtal indeed uses typedefs: https://github.com/DGtal-team/DGtal/blob/master/src/DGtal/geometry/volumes/distance/ExactPredicateLpSeparableMetric.h#L87-L95

An option would be to stop inheriting from `std::unary/binary_function`, remove `Base` typedef, and hard-code `first/second_argument` typedefs with the appropiate types.

**Comment by rolanddenis** [comment]
I also prefer the solution 4 that follow the standard evolution :+1:

**Comment by phcerdan** [comment]
#1291 follows solution 4. Remove inheritance and typedefs. The `operator()` gives the class the `unary` or `binary` behavior.
