### ISSUE TITLE
[question] Optimal way to get a digital set from an .off, .obj file, or from a DGtal::Mesh type.

### ISSUE THREAD

**Issue by phcerdan** [DGtal-team/DGtal#1289]
For example, from any file in [this repo](http://liris.cnrs.fr/meshbenchmark/) with filetypes: `.obj` or `.off`

From the [moduleIO docs](http://liris.cnrs.fr/dgtal/doc/0.9/moduleIO.html) I know there are two examples to import `.vol` and list of points to digital sets.
Also there are ways to import `off` files to `Mesh`.

What is the pathway to get a digital set from a Mesh? Thanks!

**Comment by dcoeurjo** [comment]
You would need a voxeliser for that and there is a pending PR ;)
Have a look to #1209 
Should be in 0.9.4

**Comment by dcoeurjo** [comment]
closing this question ;)
