### ISSUE TITLE
Useless code in NGon2D.ih

### ISSUE THREAD

**Issue by copyme** [DGtal-team/DGtal#1295]
There are commented lines of code :   

// double angle = 0.0;
  // if ( p[0] == 0.0 ) 
  //   {
  //     if ( p[1] >0 )
  //       angle = M_PI/2.0; 
  //     else 
  //       angle = 1.5*M_PI; 
  //   }
  // else if (  ( p[0] > 0.0 ) && (   p[1] >= 0.0 ) )
  //   angle = atan(p[1]/p[0]);
  // else if (  ( p[0] > 0.0 ) && (   p[1] <= 0.0 ) )
  //   angle = 2*M_PI + atan(p[1]/p[0]);
  // else if (  ( p[0] < 0.0 ) && (   p[1] >= 0.0 ) )
  //   angle = atan(p[1]/p[0]) + M_PI;
  // else // (  ( p[0] < 0.0 ) && (   p[1] <= 0.0 ) )
  //   angle = atan(p[1]/p[0]) + M_PI;

  // return angle;

I would suggest to remove them.

**Comment by dcoeurjo** [comment]
agree.. Please go ahead

**Comment by dcoeurjo** [comment]
Looks like it has been done..
closing.
