### ISSUE TITLE
Problems with examples/topology/ctopo-fillContours 

### ISSUE THREAD

**Issue by copyme** [DGtal-team/DGtal#1296]
When I run this code I get:

New Block [Example ctopo-fillContours]
  [ERR] Assertion Error - assertion (cIsInside( kp )) failed in Cell DGtal::KhalimskySpaceND<2, int>::uCell(const Point &) const [dim = 2, TInteger = int]: /home/kacper/tmp/DGtal-0.9.3/src/DGtal/topology/KhalimskySpaceND.ih(706)
Aborted (core dumped)

**Comment by rolanddenis** [comment]
The invalid cell is only used to get his className in order to create a CustomStyle. I though I have check all examples when adding these assertions in #1086 but it seems I have missed this one.

PR incoming. Thanks !

**Comment by rolanddenis** [comment]
Fixed in #1296, closing ...
Thanks !
