### ISSUE TITLE
QGLViewer 2.7.1 support

### ISSUE THREAD

**Issue by BorisMansencal** [DGtal-team/DGtal#1299]
Hi,

Current git head does not compile with QGLViewer 2.7.0 and 2.7.1 with Qt5 on Ubuntu 16.04 (Qt 5.5.1) and Fedora 27 (Qt 5.9.2) with QGLViewer compiled from source.

According to pr #1281 it should compile with QGLViewer 2.7.0, but small changes seem to be missing. There are two references to QGLWidget in src/DGtal/io/viewers/Viewer3D.ih despite QGLViewer does not inherit from QGLWidget since 2.7.0.  Besides, cmake/FindQGLViewer.cmake  does not find QGLViewer-qt5 library.

I have a branch in my forked repo that should fix the issue. See here https://github.com/BorisMansencal/DGtal/commit/d8d9c75b0933d0ce98e37a6add48a32eca9e4533

With DGtal, configured with: 
`ITK_DIR=/tools/InsightToolkit-4.12.2/build  cmake .. -DWITH_ITK:BOOL=ON -DWITH_OPENMP:BOOL=ON -DWITH_QGLVIEWER:BOOL=ON -DWITH_QT5:BOOL=ON -DBUILD_TESTING:BOOL=ON
` it compiles fine both on Ubuntu 16.04 and Fedora 27 with gcc and clang. I have not tested on Windows.

I should submit a PR but current git head (before my changes) does not pass the tests for my machines with this configuration.
On Ubuntu 16.04 (with clang 5.0 or gcc 5.4.0) and Fedora 27 (with clang 4.0 or gcc 7.2.1), testITKio fails.
On Ubuntu 16.04 with gcc 5.4.0, testClone2 also fails (as already reported in issue #1203 )

How should I proceed ? Should I first report the failure on testITKIO ? Should I do my PR anyway ?

**Comment by dcoeurjo** [comment]
Thanks for the report.

For the process, Please to a PR even if the CI bot or the tests fail. It would be easier for us to help you fixing the build issues.

**Comment by BorisMansencal** [comment]
I have opened PR #1300 
After merging @kerautret changes from PR #1301 and configuring also with -DWITH_HDF5:BOOL=ON on Ubuntu 16.04 (with hdf5 1.8.16), I have 6 tests failing:

> The following tests FAILED:
> 	 24 - testClone2 (Failed)
> 	149 - testITKio (Failed)
> 	157 - testGenericReader (OTHER_FAULT)
> 	162 - testHDF5Reader (OTHER_FAULT)
> 	168 - testGenericWriter (OTHER_FAULT)
> 	183 - testImageFactoryFromHDF5 (OTHER_FAULT)
>

**Comment by dcoeurjo** [comment]
closing the issue. Fixed in #1300
