### ISSUE TITLE
Webpage: SSL certificate problem

### ISSUE THREAD

**Issue by copyme** [DGtal-team/DGtal#1308]
So today I got this. 
![dgtal](https://user-images.githubusercontent.com/456607/36644010-1c0da38a-1a54-11e8-8fcd-e5b1493f247e.png)

**Comment by dcoeurjo** [comment]
I’m on it... http/https policy changes of our provider (LIRIS lab )

**Comment by dcoeurjo** [comment]
Thanks for the report

**Comment by dcoeurjo** [comment]
Fixed;)
