### ISSUE TITLE
[Question] Storing a DistanceTransformation in a single-value image.

### ISSUE THREAD

**Issue by phcerdan** [DGtal-team/DGtal#1314]
Is there a canonical way to do this?
I see that DistanceTransformation needs a TImageContainer with a TSpace::Vector, but the operator() gives the distance (The norm of the Voronoi vector).
Or do we have to create a new TImageContainer with single value type (aka, double), and populate it iterating over the Voronoi container?

Thanks!

**Comment by dcoeurjo** [comment]
Mmm I'm not sure to understand. Indeed,`DistanceTransformation`  is a facade on `VoronoiMap`, that evaluate the distances (double) from  Voronoi labelling (vector). The TImageContainer of DistanceTransform is need to be able to instantiate the underlying VoronoiMap.

DistanceTransform is a model of the Image concept, so you can directly iterate over the DT values..

**Comment by phcerdan** [comment]
Yeah, sorry about my confusing description. And thanks about the explanation, the key was to realize that DistanceTransform is a model of the Image concept, so I can directly use it in the io writer:

```cpp
  using Image = ImageContainerByITKImage<Domain, unsigned char> ;
  Image image(itk_reader->GetOutput());
  using Predicate = DGtal::functors::SimpleThresholdForegroundPredicate<Image>;
  Predicate aPredicate(image,0);
  using L3Metric = ExactPredicateLpSeparableMetric<Z3i::Space, 3>;
  L3Metric l3;
  using DT       = DistanceTransformation<Z3i::Space, Predicate, L3Metric>;
  DT dt(image.domain(),aPredicate, l3);
  /// Use DT directly in the writer because it is an Image concept.
  ITKWriter<DT>::exportITK(
          output_full_path.string().c_str(),
          dt);
```
