### ISSUE TITLE
testVoxelComplex too long

### ISSUE THREAD

**Issue by dcoeurjo** [DGtal-team/DGtal#1347]
The `testVoxelComplex` unit test is too long (40sec on my machine).
We should check if all tests are really necessary..

**Comment by dcoeurjo** [comment]
ping @phcerdan ;)

**Comment by phcerdan** [comment]
Thanks @dcoeurjo, I will have a look, I have a branch to remove the object from VoxelComplex, that will speed things up, this might be a good opportunity to bring it to the table.
