### ISSUE TITLE
Eigen issue

### ISSUE THREAD

**Issue by skn123** [DGtal-team/DGtal#1375]
Running DGTalTools, I get this error:
In file included from /usr/local/include/DGtal/dec/KForm.h:244:
/usr/local/include/DGtal/dec/KForm.ih:120:17: error: no member named 'clear' in
      'Eigen::Matrix<double, -1, 1, 0, -1, 1>'
    myContainer.clear();
    ~~~~~~~~~~~ ^

**Comment by dcoeurjo** [comment]
Very strange.. Which tool are you building?

**Comment by dcoeurjo** [comment]
Are you using the same Eigen as in #1370 ?

**Comment by skn123** [comment]
Yes I am.

**Comment by dcoeurjo** [comment]
👌  can you please try with Eigen 3.3.7?

**Comment by dcoeurjo** [comment]
see #1370

**Comment by dcoeurjo** [comment]
is this issue still open?
