### ISSUE TITLE
Any plan to have a python wrapper?

### ISSUE THREAD

**Issue by lfz** [DGtal-team/DGtal#1378]
Hi, thanks for this powerful toolbox, but I only know how to use python (sorry for that), do you have any plan to build a python wrapper for DGtal?

**Comment by dcoeurjo** [comment]
We have discussed about for many years ;). 
There have been some partial bindings  (eg using boost python bindings) but nothing more. 

In fact, we don’t have a lot of python gurus in the dev team.. 

If you want to participate, feel free 😊
