### ISSUE TITLE
NumberTraits doesn't work with `(unsigned) long long int` types

### ISSUE THREAD

**Issue by rolanddenis** [DGtal-team/DGtal#1396]
For example, `SignedVersion` and `UnsignedVersion` return wrong types with, respectively, `unsigned long long` and `signed long long` types. `CInteger` also fails with those types.

Related to https://github.com/DGtal-team/DGtal/issues/146 but those types are now in the standard (C++11).

Additionally, the `digits` values for floating-point types are wrong : it returns the number of decimal digits (e.g. `FLT_DG`) instead of the binary digits (e.g. `FLT_MANT_DIG`).

**Comment by rolanddenis** [comment]
Moreover, shouldn't `BigInteger` be unbounded?

**Comment by dcoeurjo** [comment]
( Impressive,  an #1396 issue citing a 7 year old #146 one;) )

**Comment by dcoeurjo** [comment]
`BigInteger` should be unbounded... indeed

**Comment by rolanddenis** [comment]
Thanks to the "Related issues" beta feature of GitHub :sweat_smile:

**Comment by dcoeurjo** [comment]
We should close this one, shouldn't we ?

**Comment by rolanddenis** [comment]
Yep, fixed in #1397 !
