### ISSUE TITLE
Add public .data() method to PointVector

### ISSUE THREAD

**Issue by phcerdan** [DGtal-team/DGtal#1399]
This will provide all the accesors already available of std::array: https://en.cppreference.com/w/cpp/container/array/data

https://github.com/DGtal-team/DGtal/blob/master/src/DGtal/kernel/PointVector.h#L138-L142
Const and non-const versions:

```cpp
const T* PointVector::data() const noexcept
{
return myArray.data();
}

T* PointVector::data() noexcept
{
return myArray.data();
}
```

What do you think?
It will make easier and faster to interact with other libraries accepting pointers.

I haven't checked if this will be compatible for other types of Containers (used in the library) different than the default std::array.

**Comment by dcoeurjo** [comment]
👍 that would be great, indeed.
