### ISSUE TITLE
ITK and DICOM IO limitations

### ISSUE THREAD

**Issue by BorisMansencal** [DGtal-team/DGtal#1403]
I believe that there are currently two limitations relative to ITK and DICOM IO in DGtal. They are quite orthogonal, but as they are both related to ITK, I would like to discuss them both here (possibly before 1.0 release):

- **DicomReader**: currently DGtal DICOM Reader only works with a single file. The first thing it does is to get the parent directory of the file passed as parameter and read the Dicom serie in this directory. It thus considers that there is only one DICOM serie in the directory. However, we may have several DICOM series in the same directory. Actually, very often, we have several DICOM series in the same directory. With the current API, it is not possible to specify which serie to read. I believe, that this choice of the serie to read should be done outside the reader and the reader should only load the files corresponding to the chosen serie. This is how it is done in ITK.

- **ITKReader and DicomReader**:  when an image is loaded via ITKReader or DicomReader, it looses the spatial information (spacing, origin, direction) associated to the ITK image. This behavior is expected if the ImageContainer is anything else than an ImageContainerByITKImage (an ImageContainerBySTLSomething for example). But if the destination ImageContainer is an ImageContainerByITKImage, the spatial information could be preserved. I think it should. This way, we would keep the same spatial information in an ImageContainerByITKImage loaded via DGtal (via ITKReader or DicomReader) than in an itk::Image loaded via ITK. 

I have written some code to tackle these two limitations:  
https://github.com/BorisMansencal/DGtal  **dicom** branch.

Some remarks.

The current implementation of DicomReader is quite different than ITKReader. Both load the file in a temporary itk::Image, but in DicomReader the pixel type is fixed to int32_t, whereas in ITKReader, it is read from the file.
 Besides, DicomReader is templatized on the image and the (cast) functor, while ITKReader is templatized only on the image and has a template method, templatized on the (cast) functor. 
 Finally, the test corresponding to DicomReader is not written with catch (contrary to ITKReader).

On my branch, I have changed both ITKReader and DicomReader, but also created ITKDicomReader, closer to the ITKReader code. DicomReader could be deprecated in favor of ITKDicomReader.

The code to have a different behavior for ImageContainerByITKImage and other types of image containers is more complexe, as it requires partial template specialization. It may be a problem on old Visual Studio compiler versions. But on Visual 2017 and 2019, it compiles just fine.

I have added unit tests where I check that the spatial information is the same in the ImageContainerByITKImage than in the image loaded via ITK. It seems that most of the samples files in DGtal do not have "non default" spatial information. I have added the file lobsterCropedB16b.mhd that points to the same raw file than lobsterCroped16b.mhd, but with different spatial information. We should probably also add a DICOM file with "non default" spatial information (with non uniform pixel spacings for example).

For now, I have not checked the writers. Probably that the ITK writers should also keep this spatial information in case of ImageContainerByITKImage.

What do you think ?
Do you think this modifications are desirable for DGtal 1.0 ? 
Could I submit a PR for my current branch ? Or should I submit separate PRs ?

**Comment by dcoeurjo** [comment]
hi @BorisMansencal 
thanks for the comments and your feedbacks. Indeed, we'd need to update the DICOM/ItK image wrapper.. Unfortunately, this won't be part of rel1.0 (to be presented next week ar DGCI).

**Comment by BorisMansencal** [comment]
Hi,
I have created PR #1422.
Boris.

**Comment by phcerdan** [comment]
@dcoeurjo This issue should be closed if the PR was merged.

Great stuff by the way @BorisMansencal, great to keep origin, spacing and direction of the images.

**Comment by dcoeurjo** [comment]
👌you’re right..
