### ISSUE TITLE
Error when compiling any example with QGLViewer

### ISSUE THREAD

**Issue by psarahdactyl** [DGtal-team/DGtal#1408]
I know this problem is my fault and due to my lack of CMake expertise, but I cannot figure out how to compile examples which use the 3DViewer. When running make I get:

`/usr/local/include/DGtal/io/viewers/Viewer3D.h:66:10:  fatal error: 'QGLViewer/qglviewer.h' file not found`

Is there something in my CMake that I am missing? I am using MacOS Darwin.
```
PROJECT(cc)
#Required in DGtal
CMAKE_MINIMUM_REQUIRED(VERSION 2.6)

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_SOURCE_DIR}/cmake)

FIND_PACKAGE(DGtal REQUIRED)
FIND_PACKAGE( Boost 1.40 COMPONENTS program_options REQUIRED )
find_package(Qt5Core)
find_package(Qt5Widgets)
find_package(Qt53DCore)
find_package(Qt53DExtras)
find_package(Qt53DInput)
find_package(Qt53DLogic)
find_package(Qt53DRender)

INCLUDE_DIRECTORIES(${DGTAL_INCLUDE_DIRS})
INCLUDE_DIRECTORIES( ${Boost_INCLUDE_DIR} )
   
include_directories(${Qt5Core_INCLUDE_DIRS} 
   ${Qt5Widgets_INCLUDE_DIRS} 
   ${Qt53DCore_INCLUDE_DIRS}
   ${Qt53DExtras_INCLUDE_DIRS}
   ${Qt53DInput_INCLUDE_DIRS}
   ${Qt53DLogic_INCLUDE_DIRS}
   ${Qt53DRender_INCLUDE_DIRS})

set(UI_LIBS  Qt5::Core Qt5::Widgets Qt5::3DCore Qt5::3DExtras 
   Qt5::3DExtras Qt5::3DInput Qt5::3DLogic
   Qt5::3DRender CACHE INTERNAL "" FORCE)

LINK_DIRECTORIES(${DGTAL_LIBRARY_DIRS})

ADD_EXECUTABLE(shortcuts shortcuts.cpp)

target_link_libraries(shortcuts ${UI_LIBS})
TARGET_LINK_LIBRARIES(shortcuts ${DGTAL_LIBRARIES} ${Boost_LIBRARIES})
```

**Comment by copyme** [comment]
Hi @psarahdactyl welcome to the DGtal :-) Do you have libQGLViewer installed? It is not a part of Qt distribution.

**Comment by psarahdactyl** [comment]
Hi! Thanks :) I do have it installed but I'm not sure how to make CMake find it.
In dgtal topology example CMake I see:
```
if (  WITH_VISU3D_QGLVIEWER )
   SET(DGTAL_EXAMPLES_QGL_SRC
     cubical-complex-collapse
     homotopicThinning3D
     3dBorderExtraction
     3dBorderExtractionImg
     ctopo-1-3d
     ctopo-1s-3d
     ctopo-2-3d
     3dKSSurfaceExtraction
     volScanBoundary
     volTrackBoundary
     volBreadthFirstTraversal
     frontierAndBoundary
     digitalSurfaceSlice
   )
  FOREACH(FILE ${DGTAL_EXAMPLES_QGL_SRC}) 
   add_executable(${FILE} ${FILE})
    target_link_libraries ( ${FILE}  DGtal
                            ${DGtalLibDependencies})   
  ENDFOREACH(FILE)

endif ( WITH_VISU3D_QGLVIEWER   )
```
But I can't find where `${DGtalLibDependencies}` is set in the other CMakeLists.txt(s).

**Comment by copyme** [comment]
@psarahdactyl You can try by setting these three: `QGLVIEWER_INCLUDE_DIR`, `QGLVIEWER_LIBRARIES` and `QGLVIEWER_LIBRARY_RELEASE `. But if I am not mistaken you will need to compile this against qt4. ping @dcoeurjo

**Comment by copyme** [comment]
@psarahdactyl there is a plan to replace libqglviewer in the near future because as you see it makes problems.

**Comment by psarahdactyl** [comment]
I will try setting those. 
Do you know what you'll replace it with? 
Do you know if I can access the data output in your algorithms by a face and vertex matrix? Because then I could use the libigl viewer. I was looking around a little bit and saw a halfedge data structure for the triangulated surface class and this from the mesh class:
```
 /**
     * Type to represent real points which can be obtained from  various methods (like getFaceBarycenter).
     **/
    typedef  typename DGtal::PointVector<TPoint::dimension, double> RealPoint;


    /**
     * Structure for representing the faces from the vertex index.
     **/

    typedef std::vector<unsigned int> MeshFace;


    /**
     * Define the type to store each mesh vertex.
     **/
    typedef  std::vector<TPoint> VertexStorage;

    /**
     * Define the type to store the faces of the mesh.
     **/
    typedef  std::vector<MeshFace> FaceStorage;
```

**Comment by dcoeurjo** [comment]
https://www.glfw.org is a good candidate as a replacement of libqglviewer.

For the access to the containers, it really depends on the algorithms you are using. For Meshes (or the half edge data structure), it would be pretty simple.

**Comment by dcoeurjo** [comment]
Can I close this issue too ?

**Comment by psarahdactyl** [comment]
Yes, I'll close it. I am using glfw and libigl :)
