### ISSUE TITLE
Mesh voxelization

### ISSUE THREAD

**Issue by psarahdactyl** [DGtal-team/DGtal#1410]
Hi again,
I am trying to voxelize a mesh from an STL file. First I read it in with a libigl function which gives me vertex and face matrices. Then I try to construct a Mesh from your library. however, when I voxelize it, I never get what I expect. Sometimes I get 0 voxels and for other inputs I get very low resolution results which look like only some of the mesh was voxelized.

For example for this mesh:
<img width="918" alt="Screen Shot 2019-04-28 at 1 18 05 PM" src="https://user-images.githubusercontent.com/5149074/56867815-1cd30080-69b8-11e9-9ea9-2c95c8d53e99.png">

I get:
<img width="918" alt="Screen Shot 2019-04-28 at 1 17 01 PM" src="https://user-images.githubusercontent.com/5149074/56867819-2bb9b300-69b8-11e9-9e4a-41aecc285e0b.png">

Do you think something is wrong with my mesh construction? Maybe the way I voxelize it? Does your voxelizer handle disconnected shapes?

```
#include "DGtal/base/Common.h"

#include "DGtal/helpers/Stddefs.h"
#include "DGtal/helpers/Shortcuts.h"
#include "DGtal/helpers/ShortcutsGeometry.h"
#include "DGtal/io/Display3D.h"
#include "DGtal/io/boards/Board3D.h"
#include "DGtal/shapes/Mesh.h"
#include "DGtal/io/readers/MeshReader.h"
#include "DGtal/images/imagesSetsUtils/SetFromImage.h"
#include "DGtal/shapes/MeshVoxelizer.h"

#include <boost/program_options/options_description.hpp>
#include <boost/program_options/parsers.hpp>
#include <boost/program_options/variables_map.hpp>

#include <igl/writeDMAT.h>
#include <igl/readDMAT.h>

#include <igl/readSTL.h>

#include <igl/voxel_grid.h>

#include <Eigen/Core>

using namespace std;
using namespace DGtal;
// using namespace Z3i;

// Using standard 3D digital space.
typedef Shortcuts<Z3i::KSpace>         SH3;
typedef ShortcutsGeometry<Z3i::KSpace> SHG3;

typedef int Integer;                 // choose your digital line here.
typedef SpaceND<3,Integer> Z3;       // Z^3
typedef MetricAdjacency<Z3,1> Adj6;  // 6-adjacency type
typedef Z3::Point Point;
typedef HyperRectDomain< Z3 > Domain;
typedef Domain::ConstIterator DomainConstIterator;
typedef DigitalSetSelector< Domain, BIG_DS+HIGH_BEL_DS >::Type DigitalSet;

typedef MetricAdjacency< Z3, 2 > Adj18;
typedef DigitalTopology< Adj6, Adj18 > DT6_18;
Adj6 adj6;
Adj18 adj18;
DT6_18 dt6_18( adj6, adj18, JORDAN_DT );
typedef DigitalTopology< Adj6, Adj18 > DT6_18;
typedef Object<DT6_18, DigitalSet> ObjectType;

namespace po = boost::program_options;

int main( int argc, char** argv )
{
  // parse command line ----------------------------------------------
  po::options_description general_opt("Allowed options are: ");
  general_opt.add_options()
  ("help,h", "display this message")
  ("inputFilename,f", po::value<std::string>(), "input mesh (.stl)" )
  ("outputFilename,o", po::value<std::string>(), "output obj file (.obj)" );

  bool parseOK=true;
  po::variables_map vm;
  try
  {
    po::store(po::parse_command_line(argc, argv, general_opt), vm);
  }
  catch(const std::exception& ex)
  {
    parseOK=false;
    trace.info()<< "Error checking program options: "<< ex.what()<< endl;
  }
  po::notify(vm);

  if( !parseOK || vm.count("help")||argc<=1)
  {
    std::cout << "Usage: " << argv[0] << " -f [input file] -o [output]\n"
              << "Export the boundary of a volume to OBJ format."<< endl
              << general_opt << "\n";
    return 0;
  }

  std::string inputFilename;
  std::string outputFilename;

  if(! vm.count("inputFilename"))
  {
    trace.error() << " The input file name was not defined" << endl;
    return 0;
  }

  if(! vm.count("outputFilename"))
  {
    outputFilename = "test.obj";
    return 0;
  }

  inputFilename = vm["inputFilename"].as<std::string>();
  outputFilename = vm["outputFilename"].as<string>();

  auto params = SH3::defaultParameters()
            | SHG3::defaultParameters();

  Eigen::MatrixXf V;
  Eigen::MatrixXi F;
  Eigen::MatrixXf N;
  igl::readSTL(inputFilename, V, F, N);

  Eigen::MatrixXf GV;
  Eigen::Vector3i side;
  Eigen::AlignedBox<float, 3> box(V.colwise().minCoeff(), V.colwise().maxCoeff());
  igl::voxel_grid(box, 200, 3, GV, side);
  // side is the dimensions of the voxel grid surrounding my scene
  // for the barbell it is (200,200,200)
  std::cout << side << std::endl;

  Mesh<Point> a3DMesh;

  trace.beginBlock( "Making the mesh. " );
  for(int i = 0; i < V.rows(); i++)
  { 
    auto vertex = V.row(i);
    a3DMesh.addVertex(Point(vertex(0),vertex(1),vertex(2)));
    // std::cout << "add vertex " << i << std::endl;
  }
  for(int i = 0; i < F.rows(); i++)
  {
    auto triangle = F.row(i);
    a3DMesh.addTriangularFace(triangle(0),triangle(1),triangle(2));
    // std::cout << "add face " << triangle << std::endl;
  }

  trace.endBlock();

  trace.beginBlock( "Voxelizing. " ); 
  Point p1( 0, 0, 0 );
  Point p2( side(0),side(1),side(2) );
  Domain domain( p1, p2 );
  DigitalSet outputSet( domain );

  MeshVoxelizer<DigitalSet, 6> voxelizer;
  trace.info()<<"Digitization..."<<std::endl;
  voxelizer.voxelize(outputSet, a3DMesh, 1.0);
  trace.info()<<"Got "<< outputSet.size() << " voxels."<<std::endl;

  trace.endBlock();

  Board3D<> board;
  board << SetMode3D(domain.className(), "Paving");
  board << CustomColors3D(Color(250, 0,0),Color(250, 0,0));

  for(auto voxel : outputSet)
    board << voxel;
  // board << a3DMesh;

  board.saveOBJ(outputFilename);

  return 0;
}
```

**Comment by copyme** [comment]
@psarahdactyl Can you provide the input STL file?

**Comment by psarahdactyl** [comment]
I made a new one that doesn't have planes
https://drive.google.com/open?id=1n6id-B4IyzgsnLCNMmENI4FL7XHZfGk9

**Comment by psarahdactyl** [comment]
<img width="918" alt="Screen Shot 2019-04-28 at 1 34 21 PM" src="https://user-images.githubusercontent.com/5149074/56867979-5c9ae780-69ba-11e9-8a82-28315b1f9101.png">

**Comment by copyme** [comment]
@psarahdactyl If you ask me then without trying the code (cannot right now) and just after seeing the mesh I will tell you that you have a wrong scaling factor i.e., 1, passed to the voxalizer. For this mesh, you should try something like 0.2, or smaller, maybe.

**Comment by psarahdactyl** [comment]
What exactly does the scaling factor do?

**Comment by dcoeurjo** [comment]
To relate the size of the voxel grid to the bounding box of your mesh.

**Comment by dcoeurjo** [comment]
cf https://dgtal.org/doc/stable/moduleMeshVoxelization.html: the scale factor will scale up (or down) your mesh and then will be digitize on a "unit" voxel grid

**Comment by dcoeurjo** [comment]
(https://dgtal.org/doc/stable/classDGtal_1_1MeshVoxelizer.html#a579ac9b0b2d8a79e3cf356acccb23b31)

**Comment by psarahdactyl** [comment]
with a scaling factor of 50.0, I get:
<img width="918" alt="Screen Shot 2019-04-28 at 1 45 41 PM" src="https://user-images.githubusercontent.com/5149074/56868101-0af35c80-69bc-11e9-82af-e27c28c1779c.png">
which makes me wonder if I can't voxelize disconnected meshes

**Comment by dcoeurjo** [comment]
You can play with the DGtalTools `mesh2vol` (https://github.com/DGtal-team/DGtalTools/blob/master/converters/mesh2vol.cpp)

The voxelizer processes the triangles one by one without any assumption on their connectivity.

**Comment by copyme** [comment]
@dcoeurjo @psarahdactyl ah sorry I messed up. In fact, I thought that the factor scales the grid and not the mesh. My bad.

**Comment by dcoeurjo** [comment]
(you can thus voxelize a triangle soup without any problem)

**Comment by dcoeurjo** [comment]
<img width="485" alt="Capture d’écran 2019-04-28 à 19 52 11" src="https://user-images.githubusercontent.com/700165/56868176-22980880-69ef-11e9-898b-b7f1f0984eb6.png">

**Comment by dcoeurjo** [comment]
the result I have on a 128^3 grid

**Comment by psarahdactyl** [comment]
and what scaling factor did you use? are you exporting to OBJ or is this in the viewer?

**Comment by dcoeurjo** [comment]
I've just converted the STL to OFF and run `mesh2vol -i test.off -o test.vol -r 128` (then `3dVolBoundaryViewer` to visualize the vol file)

**Comment by dcoeurjo** [comment]
if you want a 128^3 and if the STL file has the vertices  in [0,1)^3, the scale is just 128

**Comment by psarahdactyl** [comment]
ah, I see. does the resolution have to be a cube? or can my width/height/depth be different?

**Comment by dcoeurjo** [comment]
No, that is just a parameter of the DGtalTools. 

The voxelizer will use the `domain` (hyper rectangle in Z^3)  you have specified to the `outputset` (`DigitalSet outputSet( domain );`), which can have different width/height/... 

If the mesh has a huge scale factor that makes some triangles to be outside of `domain` when scaled, then they won't be voxelized.

**Comment by dcoeurjo** [comment]
BAsically, the voxelizer returns  the set of grid points in  `(scale*Mesh) \cap domain`

**Comment by psarahdactyl** [comment]
Okay! I see, that makes sense. I see the 6 and 26 connectivity; is that what you mean by stencil?

**Comment by dcoeurjo** [comment]
Exactly (template in the doc) ;)

**Comment by psarahdactyl** [comment]
Thank you both so much for your help!

**Comment by dcoeurjo** [comment]
you're welcome. Do not hesitate if you have further questions (or ping me be email).

Let me close the issue.
