### ISSUE TITLE
TOC not available anymore in the doxygen doc

### ISSUE THREAD

**Issue by dcoeurjo** [DGtal-team/DGtal#1423]
The doxygen doc pages do not contain the table-of-content anymore.

**Comment by rolanddenis** [comment]
Where did we found the table of contents ?

**Comment by dcoeurjo** [comment]
(I'm using `doxygen 1.8.15`)

**Comment by dcoeurjo** [comment]
`[TOC]` commands in module pages

**Comment by rolanddenis** [comment]
It still work with `doxygen 1.8.11` ...

**Comment by dcoeurjo** [comment]
maybe we should use `\tableofcontents` (http://www.doxygen.nl/manual/commands.html#cmdtableofcontents)

I don't remember where the `[TOC]`comes from..

**Comment by dcoeurjo** [comment]
related: https://github.com/doxygen/doxygen/issues/6513

**Comment by rolanddenis** [comment]
Yes, it seems related: we have markdown support activated and if we add a `TOC_INCLUDE_HEADINGS` directive in the doxygen configuration, the table of contents is back.

Otherwise, `\tableofcontents` works too!

**Comment by dcoeurjo** [comment]
cf #1424
