### ISSUE TITLE
boolean operations on 3D digital sets

### ISSUE THREAD

**Issue by psarahdactyl** [DGtal-team/DGtal#1430]
Are boolean operations implemented for digital sets? I want to get the intersection and the symmetric difference of 2 digital sets, but I don't know where to look in the documentation/examples.

**Comment by JacquesOlivierLachaud** [comment]
Have you tried using standard c++ algorithm template functions like std::set_symmetric_difference or std::set_intersection onto the iterators provided by DigitalSet ?

https://en.cppreference.com/w/cpp/algorithm/set_symmetric_difference

`Domain D( ... );
  DigitalSet A( D );
  DigitalSet B( D );
  DigitalSet C( D );
  // modify A and B ...
  std::set_symmetric_difference( A.begin(), A.end(), B.begin(), B.end(), C.begin() );
`

**Comment by psarahdactyl** [comment]
I will try it!

**Comment by JacquesOlivierLachaud** [comment]
Is this method working ?

**Comment by psarahdactyl** [comment]
yes, it works when the output is a stl container (otherwise it doesn't compile because it complains about operators). `std::set_intersection` works but only when I transfer everything in both sets to `std::vector`s first. I feel this shouldn't be necessary but I couldn't figure out how to do it another way. here is what I ended up with:
```
  std::vector<DGtal::PointVector<3,int>> isect;
  isect.reserve(std::min(A.size(),B.size()));
  
  std::vector<DGtal::PointVector<3,int>> set_a;
  std::vector<DGtal::PointVector<3,int>> set_b;

  for(auto&& p: A) {
      set_a.push_back(p);
  }
  for(auto&& p: B) {
      set_b.push_back(p);
  }
  std::sort(set_a.begin(), set_a.end());
  std::sort(set_b.begin(), set_b.end());

  std::set_intersection(set_a.begin(), set_a.end(), set_b.begin(), set_b.end(), std::back_inserter(isect));

  for(auto&& p: isect) {
      C.insert(p);
  }
```

**Comment by copyme** [comment]
@psarahdactyl Hi! Can you give us some exemplary code together with a CMakefile, please? I have a feeling that this should be simpler.

**Comment by dcoeurjo** [comment]
(closing, please reopen if needed)
