### ISSUE TITLE
dilation and other morphological operations on digital sets

### ISSUE THREAD

**Issue by psarahdactyl** [DGtal-team/DGtal#1435]
I see an example for FMM erosion but I was wondering if other morphological operations can be applied to digital sets as well.

**Comment by dcoeurjo** [comment]
Thanks for the fast distance field extraction algorithms (FMM https://dgtal.org/doc/1.0/moduleFMM.html or separable https://dgtal.org/doc/1.0/moduleVolumetric.html), you can easily define efficient erosion/dilation of a shape with Euclidean structuring elements. 

Although, we don't have yet any explicit API  in DGtal.

If you end up with something, do not hesitate to send us a Pull-request;)

**Comment by dcoeurjo** [comment]
(Closing, please reopen for further comments)
