### ISSUE TITLE
Split and merge Khalimsky spaces

### ISSUE THREAD

**Issue by phcerdan** [DGtal-team/DGtal#1447]
Would it be possible to split a Khalimsky space into subspaces based on geometrical points, or origin and sizes, as is doable in images?

I am trying to parallelize an algorithm that is applied to a CubicalComplex, which is a subset of a KhalimskySpace.
A regular image, as any structured grid,  can be easily split into subimages, however I guess is not that easy when using Khalimsky spaces. But still, I wonder if is it possible and how.

**Comment by JacquesOlivierLachaud** [comment]
In fact, a KhalimskySpace is different from an image in the sense that it does not hold data, it is just a way to model elements (cells) of the discrete space in a more abstract way than just playing with coordinates.
Then if you wish to create subspaces, you can just init them with different low and up points (and choose well if you want to close or open them). You can also convert coordinates to PreKhalimskySpace, which is a "universal" way for representing cells (thanks to @rolanddenis ).
Have I well understood your question ?

**Comment by phcerdan** [comment]
> Have I well understood your question ?

Yes! Thanks @JacquesOlivierLachaud.

My doubts are on how to "link" the original space and the subspaces. Thinking out-loud with an example:
Original KSpace: LoweBound: (0,0) ; UpperBound: (4,4)
Sub1 : LowerBound: (0,0); UpperBound: (2,4)
Sub2 : LowerBound: (2,0); UpperBound: (4,4)

```
   Original KSpace
     __ __ __ __ (4,4)
    |         |         |
    |  S1   |  S2  |
    |         |         |
    |__ __|__ __|
(0,0)    (2,0)
```

Sub1 and Sub2 would have its own Khalimsky coordinates, unrelated to Original I guess (?), so if after manipulation of Sub1, I want to merge it back to Original, how would I do it?

**Comment by phcerdan** [comment]
Ok,I think I get it now, the coordinates are indeed related, I got confused with the concept of "index" in an image, which is an internal representation.
In KSpaces the zero index is the LowerBound itself.

Thanks for reading! :P
