### ISSUE TITLE
Static assertion raised in SegmentFactory when using SaturatedSegmentation

### ISSUE THREAD

**Issue by nyorem** [DGtal-team/DGtal#1483]
Hi all,

I tried to use the `SaturatedSegmentation` class with a `StandardDSS4Computer` namely the following typedefs (for instance in lines 173-174 the [convex-and-concave-parts example](https://dgtal.org/doc/stable/convex-and-concave-parts_8cpp_source.html)):
```
typedef StandardDSS4Computer<Iterator> RecognitionAlgorithm;
typedef SaturatedSegmentation<RecognitionAlgorithm> Segmentation;
```

and it raised a static assertion in `SegmentFactory`:
```
/path/to/DGtal/src/DGtal/geometry/curves/CSegmentFactory.h:98:56: error: static assertion failed: ( boost::is_same< T, Self >::value )
   98 |       BOOST_STATIC_ASSERT(( boost::is_same< T, Self >::value ));
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~ 
```

Using an `ArithmeticalDSSComputer<Iterator,Coordinate,4>` for the `RecognitionAlgorithm` does not raise this error.

As far as I understand `SaturatedSegmentation` should work with any kind of `SegmentComputer` such as `StandardDSS4Computer` or am I wrong?

Thank you in advance.

**Comment by rolanddenis** [comment]
Hi Jocelyn and sorry for the delay :wink: 

From what I understand from these classes, `StandardDSS4Computer` is just an alias to `ArithmeticalDSSComputer` with a adjacency 4. It has been implemented as a derived class whose `Self`typedef does not match the actual class leading to the concept check error that you have.

While waiting for a fix, I suggest you to use the corresponding alias, that is the same line as in the original example:
```C++
typedef ArithmeticalDSSComputer<Iterator,Coordinate,4> RecognitionAlgorithm;
```
or if you prefer, to get the real type using the `Self`or `Super`typedef (the ugly solution):
```C++
typedef typename StandardDSS4Computer<Iterator>::Self RecognitionAlgorithm;
```

**Comment by nyorem** [comment]
No worries for the delay!

Thank you for your answer, I already used your first proposition to solve the issue but a real fix would be better :wink:

**Comment by rolanddenis** [comment]
Ongoing fix : #1491

**Comment by rolanddenis** [comment]
Should be fixed, I close the issue!

**Comment by nyorem** [comment]
Thanks!
