### ISSUE TITLE
CI failures because Eigen download

### ISSUE THREAD

**Issue by phcerdan** [DGtal-team/DGtal#1507]
Bitbucket download links are broken: https://bitbucket.org/eigen/eigen/get/3.2.10.tar.bz2

Eigen moved to gitlab: https://gitlab.com/libeigen/eigen

The url should be updated to something like: https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.bz2

**Comment by dcoeurjo** [comment]
ouch.. thanks for the report.
