### ISSUE TITLE
CI: DGtal-team.DGtal Expected — Waiting for status to be reported 

### ISSUE THREAD

**Issue by phcerdan** [DGtal-team/DGtal#1545]
It is reported here:
https://github.community/t/azure-pipelines-2-copies-stuck-expected-waiting-for-status-to-be-reported/18380/6

The workaround seems to disable the pipeline check (but let the others):
![image](https://user-images.githubusercontent.com/3021667/104590376-88b53b00-566b-11eb-937d-7c2ff7956a75.png)

**Comment by dcoeurjo** [comment]
Thanks @phcerdan, done ;)
