### ISSUE TITLE
Timing issue for testPlaneProbingParallelepipedEstimator

### ISSUE THREAD

**Issue by dcoeurjo** [DGtal-team/DGtal#1552]
Following  https://github.com/DGtal-team/DGtal/pull/1547, the unit test is 12min long on travis (which is a lot for a unit test).

@nyorem @JacquesOlivierLachaud

**Comment by dcoeurjo** [comment]
https://github.com/DGtal-team/DGtal/pull/1547#issuecomment-784296860

**Comment by JacquesOlivierLachaud** [comment]
Oups, I did not see that.

**Comment by nyorem** [comment]
Sorry, I was checking unit tests when compiled in Release mode, I'll submit a PR shortly.

**Comment by dcoeurjo** [comment]
Thanks !
