### ISSUE TITLE
Qt5 issue on MacOS

### ISSUE THREAD

**Issue by dcoeurjo** [DGtal-team/DGtal#1574]
I'm having issues with qt@5 on mac (homebrew). The current package seems to require C++14 or c++17 std.

@kerautret @JacquesOlivierLachaud do you have the same issues ?

**Comment by kerautret** [comment]
I am using a local installation of Qt5, I can try to switch if you want

**Comment by dcoeurjo** [comment]
After installing qt@5 with homebrew (you can remove later) and the following cmake:

       cmake .. -DCMAKE_PREFIX_PATH=$(brew --prefix qt5)  -DWITH_QT5=true  -DWITH_QGLVIEWER=true

are you able to build the project ?

**Comment by kerautret** [comment]
let me try

**Comment by kerautret** [comment]
That is fine for me...  Numerous usual OpenGL warning..
<img width="738" alt="Capture d’écran 2021-05-28 à 15 47 53" src="https://user-images.githubusercontent.com/772865/119993631-13b82180-bfcc-11eb-98a4-dbf7263d30f3.png">

**Comment by dcoeurjo** [comment]
Ok the issue comes from having `qt` (current version is 6) and `qt@5` in homebrew.
Removing qt (@6) and reinstalling `qt@5` solve the problem.
