### ISSUE TITLE
Issue of linking on DGtal website

### ISSUE THREAD

**Issue by ngophuc** [DGtal-team/DGtal#1606]
I write to report you that there are problems with the links in official website of dgtal, in particular: https://dgtal.org/aboutme/ in the section "Features Digital Geometry Tools and Algorithms".
All links in this section, except the first one of DGtal, are in 404 error (this page doesn't exist.
Move along. (404 error)).

**Comment by dcoeurjo** [comment]
Oh I see... thanks for the report.

**Comment by dcoeurjo** [comment]
This has been fixed. thanks for the issue.
