### ISSUE TITLE
testStabbingCircleComputer failing

### ISSUE THREAD

**Issue by dcoeurjo** [DGtal-team/DGtal#1676]
Cf https://github.com/DGtal-team/DGtal/actions/runs/3836135851/jobs/6529980104 
On my computer, there is no problem but GithubBots have issues with this test.

@troussil could you please have a look ?

**Comment by troussil** [comment]
tested with Ubuntu 22.04.1 LTS : 
- works fine in Debug
- fails in Release mode
I disable the test (see  #1679 ) until we find the bug (it's in my TODO list)

**Comment by troussil** [comment]
Here is the result of my investigation : it's a numerical issue. Indeed all tests pass with int64_t or BigInteger as a coordinate type and whatever the mode is (Debug or Release). I'm waiting PR #1681 to change the test because it is better to not default-construct KhalimskySpace.

**Comment by dcoeurjo** [comment]
👌 #1681 has been merged.

**Comment by troussil** [comment]
done in PR #1688
