### ISSUE TITLE
Reactivate unit-test on windows

### ISSUE THREAD

**Issue by dcoeurjo** [DGtal-team/DGtal#1693]
Commented at this point in the GitHub scripts. Only the build is performed.

(Find executable issue)

**Comment by kerautret** [comment]
I suppose that it is related to the window \ interpretation in path ?

**Comment by dcoeurjo** [comment]
If I remember correctly, it was due to duplicate objects generated by VS. 
we should probably have a look to that on a dedicated PR

**Comment by kerautret** [comment]
I get it ;)  on PR #1706

**Comment by dcoeurjo** [comment]
Fixed! many thanks

**Comment by kerautret** [comment]
yes ;) you are welcome!
