### ISSUE TITLE
DGMM tutorial keynote and pdf file missing  

### ISSUE THREAD

**Issue by kerautret** [DGtal-team/DGtal#1703]
The link on DGMM tutorials presentation looks broken https://dgtal.org/documentation/ 
![Capture d’écran 2023-10-11 à 18 26 49](https://github.com/DGtal-team/DGtal/assets/772865/a5e1fc99-7078-4e32-acee-3c8e1f869cdf)

**Comment by dcoeurjo** [comment]
Ok should be fixed now. Thanks for the issue
