### ISSUE TITLE
Test fails testArithmeticalDSSComputerOnSurfels 

### ISSUE THREAD

**Issue by kerautret** [DGtal-team/DGtal#1707]
As shown here: https://github.com/DGtal-team/DGtal/actions/runs/6628647243/job/18006199499
testArithmeticalDSSComputerOnSurfels fails on windows and at least also on MacOS
![Capture d’écran 2023-10-24 à 18 07 42](https://github.com/DGtal-team/DGtal/assets/772865/66a68b11-177d-42c1-b162-0737480d002d)

**Comment by dcoeurjo** [comment]
Yes I've already had some issues with this test. Maybe @troussil would know

**Comment by troussil** [comment]
@kerautret I cannot reproduce the error on my computer. Could you send the complete error message?

**Comment by kerautret** [comment]
thanks @troussil, yes here is the previous level: It you want I can make a screen video of each level of we can make a call with and sharing Xcode interface
![Capture d’écran 2023-11-24 à 10 52 29](https://github.com/DGtal-team/DGtal/assets/772865/23c20dd4-f184-405a-9088-ee29ec57a4da)
