### ISSUE TITLE
Compilation pb  WITH magick/cpp11

### ISSUE THREAD

**Issue by kerautret** [DGtal-team/DGtal#406]
Have you a problem with the option WITH_MAGICK ? I am not sure that it is recent or not ...

[ 57%] Building CXX object tests/io/readers/CMakeFiles/testRawReader.dir/testRawReader.cpp.o
[ 57%] Building CXX object tests/io/readers/CMakeFiles/testVolReader.dir/testVolReader.cpp.o
In file included from /opt/local/lib/gcc46/gcc/x86_64-apple-darwin11/4.6.2/include/xmmintrin.h:36:0,
                 from /opt/local/lib/gcc46/gcc/x86_64-apple-darwin11/4.6.2/include/emmintrin.h:36,
                 from /opt/local/include/boost/math/special_functions/detail/lanczos_sse2.hpp:13,
                 from /opt/local/include/boost/math/special_functions/lanczos.hpp:1234,
                 from /opt/local/include/boost/math/special_functions/gamma.hpp:39,
                 from /opt/local/include/boost/math/special_functions/factorials.hpp:13,
                 from /opt/local/include/boost/math/special_functions/binomial.hpp:13,
                 from /Users/kerautre/EnCours/DGtal/src/DGtal/topology/MetricAdjacency.ih:33,
                 from /Users/kerautre/EnCours/DGtal/src/DGtal/topology/MetricAdjacency.h:259,
                 from /Users/kerautre/EnCours/DGtal/src/DGtal/topology/DomainAdjacency.ih:37,
                 from /Users/kerautre/EnCours/DGtal/src/DGtal/topology/DomainAdjacency.h:276,
                 from /Users/kerautre/EnCours/DGtal/src/DGtal/topology/Expander.h:47,
                 from /Users/kerautre/EnCours/DGtal/src/DGtal/topology/Object.ih:34,
                 from /Users/kerautre/EnCours/DGtal/src/DGtal/topology/Object.h:616,
                 from /Users/kerautre/EnCours/DGtal/src/DGtal/io/Display2DFactory.h:61,
                 from /Users/kerautre/EnCours/DGtal/src/DGtal/io/boards/Board2D.h:441,
                 from /Users/kerautre/EnCours/DGtal/tests/io/readers/testMagickReader.cpp:43:
/opt/local/lib/gcc46/gcc/x86_64-apple-darwin11/4.6.2/include/mmintrin.h: In function '__m64 _mm_cvtsi32_si64(int)':
/opt/local/lib/gcc46/gcc/x86_64-apple-darwin11/4.6.2/include/mmintrin.h:62:54: error: can't convert between vector values of different size
/opt/local/lib/gcc46/gcc/x86_64-apple-darwin11/4.6.2/include/mmintrin.h: In function 'int _mm_cvtsi64_si32(__m64)':
/opt/local/lib/gcc46/gcc/x86_64-apple-darwin11/4.6.2/include/mmintrin.h:105:53: error: cannot convert '__m64 {aka int}' to '__vector(2) int' for argument '1' to 'int __builtin_ia32_vec_ext_v2si(__vector(2) int, int)'
/opt/local/lib/gcc46/gcc/x86_64-apple-darwin11/4.6.2/include/mmintrin.h: In function '__m64 _mm_packs_pi16(__m64, __m64)':
/opt/local/lib/gcc46/gcc/x86_64-apple-darwin11/4.6.2/include/mmintrin.h:144:69: error: cannot convert '__v4hi {aka short int}' to '__vector(4) short int' for argument '1' to '__vector(8) char __builtin_ia32_packsswb(__vector(4) short int, __vector(4) short int)'
/opt/local/lib/gcc46/gcc/x86_64-apple-darwin11/4.6.2/include/mmintrin.h: In function '__m64 _mm_packs_pi32(__m64, __m64)':
/opt/local/lib/gcc46/gcc/x86_64-apple-darwin11/4.6.2/include/mmintrin.h:159:69: error: cannot convert '__m64 {aka int}' to '__vector(2) int' for argument '1' to '__vector(4) short int __builtin_ia32_packssdw(__vector(2) int, __vector(2) int)'
/opt/local/lib/gcc46/gcc/x86_64-apple-darwin11/4.6.2/include/mmintrin.h: In function '__m64 _mm_packs_pu16(__m64, __m64)':
/opt/local/lib/gcc46/gcc/x86_64-apple-darwin11/4.6.2/include/mmintrin.h:174:69: error: cannot convert '__v4hi {aka short int}' to '__vector(4) short int' for argument '1' to '__vector(8) char __builtin_ia32_packuswb(__vector(4) short int, __vector(4) short int)'

**Comment by dcoeurjo** [comment]
works fine for me.. closing this issue
