### ISSUE TITLE
Replace QGLviewer with QT3D  framework ?

### ISSUE THREAD

**Issue by kerautret** [DGtal-team/DGtal#621]
I was wondering if we could try to change the dependancies of QGLViewer with QT5 3D possibility ? 
@mtola you mention it last year, but now since the version 5 is perhaps stabilized, it could be interesting to test ? The advantage is that it remove the dependancy of qglviewer which looks not updated since a year. The potential viewer looks comparable at first view.
@mtola  have you test it? 
By the way @dcoeurjo  I don't remember if the OGRE branch was ready to be merged ?

**Comment by dcoeurjo** [comment]
Closing this issue, let's wait a little bit  for QT5-QT3D

**Comment by mtola** [comment]
I'm not working on DGtal for now but just to tell you that qt3d is now out for the first time (Technology Preview) since this summer in qt 5.5:
http://www.kdab.com/qt3d-technology-preview-released-qt-5-5-0/
