### ISSUE TITLE
Bug when importing Image with ImageContainerBySTLMap and DicomReader

### ISSUE THREAD

**Issue by kerautret** [DGtal-team/DGtal#779]
When applying:
typedef DGtal::ImageContainerBySTLMap<DGtal::Z3i::Domain, unsigned char> Image3D;
typedef DGtal::RescalingFunctor<int ,unsigned char > RescalFCT;

 Image3D imageVol = DicomReader< Image3D,  RescalFCT  >::importDicom(inputFilename, RescalFCT(-900,
                                                                                               530,
                                                                                               0, 255));

The resulting domain is totally wrong!... While replacing ImageContainerBySTLMap by ImageContainerBySTLVector it is ok !....

**Comment by isivigno** [comment]
I just encountered the same kind of problem with the importPGM reader : 

typedef ImageContainerBySTLMap<Z2i::Domain, unsigned char> Image;
Image image = DGtal::PGMReader<Image>::importPGM("../circleR10modif.pgm");   
Board2D board;
typedef GrayscaleColorMap<unsigned char> Gray;
Display2DFactory::drawImage<Gray>(board, image, (unsigned int)0, (unsigned int)129);  
---> assertion fails 

The good news is that it works if you use the GenericReader: 
Image image = DGtal::GenericReader<Image>::import("../circleR10modif.pgm");

**Comment by JacquesOlivierLachaud** [comment]
Should be fixed by #1151. Is it the case ?

**Comment by kerautret** [comment]
I look it ;)

**Comment by JacquesOlivierLachaud** [comment]
Thanks!

**Comment by kerautret** [comment]
yes all looks fine !
With dicom2vol compiled with STLMap:

./converters/dicom2vol -i ../../DGtal/tests/samples/dicomSample/1629.dcm -o tmp.vol
Reading input dicom file ../../DGtal/tests/samples/dicomSample/1629.dcm [done] 
 converting into vol file...  [done] 
And the vol looks fine:
./visualisation/3dImageViewer -i tmp.vol  --thresholdImage -m 0 -M 63
Image loaded: [Image - STLVector] size=2130048 valuetype=1bytes Domain=[HyperRectDomain] = [[PointVector] {0, 0, 0}]x[[PointVector] {128, 127, 128}]

**Comment by JacquesOlivierLachaud** [comment]
Perfect. Merging.

**Comment by JacquesOlivierLachaud** [comment]
Closing issue
