### ISSUE TITLE
Transformations of images rigid, affine, etc

### ISSUE THREAD

**Issue by copyme** [DGtal-team/DGtal#813]
It will be nice to see these transformations in the near future in DGtal.

But probably is good to mention that right now I am working on rigid transformations and 3D images and my code uses DGtal, so I can redesign it a bit to get better compatibility with DGtal and also write a code for 2D. So far I have:

+ Rotation around arbitrary axis with Rodrigues' rotation formula
+ Eulerian and Lagrangian model
+ Conversion from Eulerian angle to Pythagorean one with rational number representation(GMP) - includes an algorithm to approximate given number to rational approximation
+ translation
+ Exact allocation of output image

**Comment by dcoeurjo** [comment]
Can I close this issue ? 
CC @copyme

**Comment by dcoeurjo** [comment]
ping @copyme, can i close this issue?

**Comment by copyme** [comment]
@dcoeurjo With shame I have to say I had no time to work on this issue. Let close it and if in the meanwhile I will have time to finish a port of your code I will re-open it.
