### ISSUE TITLE
Hidden axis in the 3D scene produced by Viewer3D

### ISSUE THREAD

**Issue by copyme** [DGtal-team/DGtal#873]
Axis in the 3D scene can be invisible because overlapping with objects sent to the Viewer3D.

![axis](https://cloud.githubusercontent.com/assets/456607/3483855/8200c136-0397-11e4-9622-4faf527acb5b.png)

**Comment by kerautret** [comment]
@copyme should be fixes from PR #1108 , you confirm ?

**Comment by kerautret** [comment]
I close it, should be fine now, @copyme re open if needed.
