### ISSUE TITLE
OBJs generated by Board3D are not sufficiently exact

### ISSUE THREAD

**Issue by copyme** [DGtal-team/DGtal#900]
The Board3D export by default grid edges but they do not look good. As a demo see: http://www.esiee.fr/~plutak/embedded_sphere_r_1_bad.html
These edges are not even straight:

![nonstr_edges](https://cloud.githubusercontent.com/assets/456607/3857379/b03e6982-1f02-11e4-8f9c-6f76d8f23893.png)

also notice that the output object looks like from a cartoon. This problem is maybe also related to the normals and rendering.

**Comment by dcoeurjo** [comment]
@kerautret I think you have solved this, don't you ?

**Comment by kerautret** [comment]
yes for the vertex order/faces, but concerning flat line I am not sure that it was improved.

**Comment by dcoeurjo** [comment]
@copyme is this issue still open?
