### ISSUE TITLE
 viewer3D-8-2DSliceImages + viewer3D-9-3Dimages  give an error

### ISSUE THREAD

**Issue by kerautret** [DGtal-team/DGtal#931]
Scene radius must be positive - Ignoring value
[ERR] Assertion Error - assertion (( false && "[ConstAlias::ConstAlias( T&& )] Const-aliasing a rvalue ref has no meaning. Consider Clone instead." )) failed in DGtal::ConstAlias<hueFct>::ConstAlias(T &&) [T = hueFct]: /Users/kerautre/EnCours/DGtal/src/DGtal/base/ConstAlias.h(259)
Abort trap: 6

**Comment by dcoeurjo** [comment]
Confirmed..

**Comment by kerautret** [comment]
closing that merged ;)
