### ISSUE TITLE
Quad Color exports in Board3D does not work anymore 

### ISSUE THREAD

**Issue by dcoeurjo** [DGtal-team/DGtal#943]
due to https://github.com/DGtal-team/DGtal/commit/05c5f89628d8806fc4f5468825c11d03d37b11b7 apparently

**Comment by JacquesOlivierLachaud** [comment]
Do you have a corresponding example/test in mind ?

**Comment by dcoeurjo** [comment]
You can have a look to testBoard3d (I don't know if colors are tested). Otherwise, 3dcurvatureviewer with export in dgtaltools

**Comment by kerautret** [comment]
I fix it ;)
In fact the Display3D subclass Board3D was not updated with new Jaco QuadMap.
I update it for the export (in PR #946). For the color,I have adapted the commented createNewQuadList of Display3d with a simple search ok an empty key and an update of the name3d attribute. It works with see DGtalTools PR #194

**Comment by dcoeurjo** [comment]
Hi, I'm not sure to understand. Is the fix to ask the user to add a createNewQuadList  every time he wants to change the color (which is not great IMHO) ?

Why this fix/issue only appears for quad and not other shapes ?

Before your commits in December, this was done in CustomColors3D or setPen (if I remember correctly).

**Comment by dcoeurjo** [comment]
As far as I remember, lists were used in board3d with the following semantic: objects within a list share the same material (to reduce MTL filesize). Now, it may be deprecated since I use now a std::map for material. 

Anyway, what is the semantic you attach to lists in your recent PR?

**Comment by kerautret** [comment]
"Hi, I'm not sure to understand. Is the fix to ask the user to add a createNewQuadList every time he wants to change the color (which is not great IMHO) ?"
=> Hi, 
yes, initially it is inside the drawing factory but it was deactivated in the Jaco PR with map. I can un comment it it should work.
"Why this fix/issue only appears for quad and not other shapes ?"
=> For now just the Quad3D can deal with interaction using map, so for me the global final transformation should be better to be done it in another PR with more semantic discussions between interaction/list.

"Before your commits in December, this was done in CustomColors3D or setPen (if I remember correctly)."
=> It always the case a CustomColors3D implies a new list, It is not the fix itself, it is the case from a long time, once the user use

**Comment by kerautret** [comment]
"As far as I remember, lists were used in board3d with the following semantic: objects within a list share the same material (to reduce MTL filesize). Now, it may be deprecated since I use now a std::map for material."
=> yes it is
"Anyway, what is the semantic you attach to lists in your recent PRs?"
=> I add nothing new just putting again the list creation (temporary before list removing?)

**Comment by kerautret** [comment]
For now, If you want I can just hide again the list creation inside the 3Dfactory (as done with old list) which will be finer for user and add an issue about the list->maps fusion/cohabitation in Display3D ?

**Comment by kerautret** [comment]
the proposed fix transparent for the user:
https://github.com/kerautret/DGtal/commit/99728e7b4c77186a568ff7e65d2e309b282d795d

**Comment by dcoeurjo** [comment]
fixed in master. closing
