### ISSUE TITLE
Example dgtalboard-5-greedy-dss  produces eps file with error

### ISSUE THREAD

**Issue by kerautret** [DGtal-team/DGtal#954]
(tested on mac (gv, inskape) and linux (gv),
However the svg is ok, I don't see the pb... ;(

**Comment by dcoeurjo** [comment]
@kerautret I don't see where this example code is.

**Comment by troussil** [comment]
The example is called in fact greedy-dss-decomposition.cpp.
See PR #956

2015-02-18 9:31 GMT+01:00 David Coeurjolly <notifications@github.com>:

**Comment by kerautret** [comment]
That was corrected and merged I close
