### ISSUE TITLE
exampleArithmeticalDSL  fails

### ISSUE THREAD

**Issue by kerautret** [DGtal-team/DGtal#959]
It produce an error at the end:
 ./examples/geometry/curves/exampleArithmeticalDSL 
New Block [Example exampleArithmeticalDSL]
  Args:   ./examples/geometry/curves/exampleArithmeticalDSL  
  New Block [Naive DSL]
    [ArithmeticalDSL] (2,5,0,5)
by steps [PointVector] {1, 0} [PointVector] {1, 1}
[ArithmeticalDSL] (-2,-5,-4,5)
by steps [PointVector] {-1, 0} [PointVector] {-1, -1}
  EndBlock [Naive DSL] (18.673 ms)
  New Block [Standard DSL]
    [ArithmeticalDSL] (2,5,0,7)
by steps [PointVector] {1, 0} [PointVector] {0, 1}
[ArithmeticalDSL] (-2,-5,-6,7)
by steps [PointVector] {-1, 0} [PointVector] {0, -1}
  EndBlock [Standard DSL] (6.928 ms)
  New Block [ Arithmetical DSL (0, 1, 0) in octant 0]
  EndBlock [ Arithmetical DSL (0, 1, 0) in octant 0] (2.969 ms)
  New Block [ Arithmetical DSL (5, 8, 0) in octant 0]
  EndBlock [ Arithmetical DSL (5, 8, 0) in octant 0] (15.027 ms)
  New Block [ Arithmetical DSL (1, 1, 0) in octant 1]
  EndBlock [ Arithmetical DSL (1, 1, 0) in octant 1] (26.618 ms)
  New Block [ Arithmetical DSL (8, 5, 0) in octant 1]
  EndBlock [ Arithmetical DSL (8, 5, 0) in octant 1] (16.487 ms)
  New Block [ Arithmetical DSL (1, 0, 0) in octant 2]
  EndBlock [ Arithmetical DSL (1, 0, 0) in octant 2] (3.659 ms)
  New Block [ Arithmetical DSL (8, -5, 0) in octant 2]
  EndBlock [ Arithmetical DSL (8, -5, 0) in octant 2] (17.331 ms)
  New Block [ Arithmetical DSL (1, -1, 0) in octant 3]
  EndBlock [ Arithmetical DSL (1, -1, 0) in octant 3] (24.591 ms)
  New Block [ Arithmetical DSL (5, -8, 0) in octant 3]
  EndBlock [ Arithmetical DSL (5, -8, 0) in octant 3] (15.346 ms)
  New Block [ Arithmetical DSL (0, -1, 0) in octant 4]
  EndBlock [ Arithmetical DSL (0, -1, 0) in octant 4] (4.517 ms)
  New Block [ Arithmetical DSL (-5, -8, 0) in octant 4]
  EndBlock [ Arithmetical DSL (-5, -8, 0) in octant 4] (19.852 ms)
  New Block [ Arithmetical DSL (-1, -1, 0) in octant 5]
  EndBlock [ Arithmetical DSL (-1, -1, 0) in octant 5] (21.752 ms)
  New Block [ Arithmetical DSL (-8, -5, 0) in octant 5]
  EndBlock [ Arithmetical DSL (-8, -5, 0) in octant 5] (16.738 ms)
  New Block [ Arithmetical DSL (-1, 0, 0) in octant 6]
  EndBlock [ Arithmetical DSL (-1, 0, 0) in octant 6] (4.171 ms)
  New Block [ Arithmetical DSL (-8, 5, 0) in octant 6]
  EndBlock [ Arithmetical DSL (-8, 5, 0) in octant 6] (15.265 ms)
  New Block [ Arithmetical DSL (-1, 1, 0) in octant 7]
  EndBlock [ Arithmetical DSL (-1, 1, 0) in octant 7] (22.02 ms)
  New Block [ Arithmetical DSL (-5, 8, 0) in octant 7]
  EndBlock [ Arithmetical DSL (-5, 8, 0) in octant 7] (14.9 ms)
  New Block [ Arithmetical DSL (0, 1, 0) in octant 0]
  EndBlock [ Arithmetical DSL (0, 1, 0) in octant 0] (4.314 ms)
  New Block [ Arithmetical DSL (5, 8, 0) in octant 0]
  EndBlock [ Arithmetical DSL (5, 8, 0) in octant 0] (12.33 ms)
  New Block [ Arithmetical DSL (1, 1, 0) in octant 1]
  EndBlock [ Arithmetical DSL (1, 1, 0) in octant 1] (11.889 ms)
  New Block [ Arithmetical DSL (8, 5, 0) in octant 1]
  EndBlock [ Arithmetical DSL (8, 5, 0) in octant 1] (11.211 ms)
  New Block [ Arithmetical DSL (1, 0, 0) in octant 2]
  EndBlock [ Arithmetical DSL (1, 0, 0) in octant 2] (5.631 ms)
  New Block [ Arithmetical DSL (8, -5, 0) in octant 2]
  EndBlock [ Arithmetical DSL (8, -5, 0) in octant 2] (11.672 ms)
  New Block [ Arithmetical DSL (1, -1, 0) in octant 3]
  EndBlock [ Arithmetical DSL (1, -1, 0) in octant 3] (12.719 ms)
  New Block [ Arithmetical DSL (5, -8, 0) in octant 3]
  EndBlock [ Arithmetical DSL (5, -8, 0) in octant 3] (12.867 ms)
  New Block [ Arithmetical DSL (0, -1, 0) in octant 4]
  EndBlock [ Arithmetical DSL (0, -1, 0) in octant 4] (3.856 ms)
  New Block [ Arithmetical DSL (-5, -8, 0) in octant 4]
Segmentation fault: 11

**Comment by troussil** [comment]
Everything's fine on my computer (example built with g++)
Do you have more information (backtrace with gdb for instance) ?

**Comment by dcoeurjo** [comment]
Fine for me. @kerautret any backtrace ?

**Comment by kerautret** [comment]
You will laugh but it also fine for me now ;) Perhaps it was already corrected... (clang-602.0.53)

**Comment by kerautret** [comment]
I close it ;à)
