### ISSUE TITLE
missing examples in "examples" section of doxygen doc

### ISSUE THREAD

**Issue by kerautret** [DGtal-team/DGtal#960]
Some examples are not visible in http://liris.cnrs.fr/dgtal/doc/nightly/examples.html
In particular the ones of examples/geometry/curves/
(exampleArithDSS3d, exampleArithmeticalDSL, exampleArithmeticalDSSComputer, exampleDSLSubsegment, exampleFrechetShortcut, exampleGridCurve2d, exampleGridCurve3d, exampleGridCurve3d-2, exampleStabbingCircleComputer, exampleStabbingLineComputer)

You can just add in moduleArithDSSReco.dox something like this example:
/**
This example shows the recognition of a simple standard digital
plane with the Chord algorithm (class
ChordGenericStandardPlaneComputer ). Green points belong to the naive
plane. Grey points show farther points that also belong to the
strip.

@see \ref modulePlaneRecognition_sec26

@verbatim
$ ./examples/io/viewers/viewer3D-7bis-stdplane
@endverbatim

@image html coba-stdplane.png "Piece of standard plane."
@image latex coba-stdplane.png "Piece of standard plane." width=5cm

\example io/viewers/viewer3D-7bis-stdplane.cpp
*/

**Comment by troussil** [comment]
done, see  #1026

**Comment by dcoeurjo** [comment]
Fixed.
