### ISSUE TITLE
greedy-plane-segmentation-ex2 fails at display

### ISSUE THREAD

**Issue by kerautret** [DGtal-team/DGtal#964]
I have an error when testing the example greedy-plane-segmentation-ex2:
[ERR] Assertion Error - assertion (myCellEmbedder->isValid()) failed in RealPoint DGtal::Display3D<DGtal::SpaceND<3, int>, DGtal::KhalimskySpaceND<3, int> >::embedK(const typename KSpace::Cell &) const [S = DGtal::SpaceND<3, int>, KS = DGtal::KhalimskySpaceND<3, int>]: /Users/kerautre/EnCours/DGtal/src/DGtal/io/Display3D.ih(1226)

**Comment by kerautret** [comment]
also same with greedy-plane-segmentation-ex3

**Comment by JacquesOlivierLachaud** [comment]
Ok. I look at it.

**Comment by kerautret** [comment]
fixed, https://github.com/DGtal-team/DGtal/pull/967
