### ISSUE TITLE
Point (ball) size looks too big in viewer3D-6-clipping 

### ISSUE THREAD

**Issue by kerautret** [DGtal-team/DGtal#965]
We obtain such visu:
![capture d ecran 2015-02-25 a 11 03 55](https://cloud.githubusercontent.com/assets/772865/6368573/345b4590-bcde-11e4-880b-92129da941a1.png)
Instead this one:
http://liris.cnrs.fr/dgtal/doc/nightly/io_2viewers_2viewer3D-6-clipping_8cpp-example.html

**Comment by dcoeurjo** [comment]
ok I see.. I may have changed default radius parameter. Let me check

**Comment by dcoeurjo** [comment]
done in #978

**Comment by dcoeurjo** [comment]
solved
