### ISSUE TITLE
Move MPolynomial Reader  to an optional feature

### ISSUE THREAD

**Issue by dcoeurjo** [DGtal-team/DGtal#975]
There are too much issues between boost::spirit, GCC and Polynomial stuff in DGtal. Travis has a non-deterministic behavior when building the lib on GCC.

I suggest to move the reader to as an optional tool activated using a WITH_POLYNOMIAL flag at cmake stage. 

This is straightforward but may impact  several classes and tools

cc @kerautret @JacquesOlivierLachaud

**Comment by JacquesOlivierLachaud** [comment]
I agree boost::spirit is a problem. Perhaps the flag could be called
WITH_POLYNOMIAL_PARSER, but, for users, to put the flag ON by default.
What do you think ?

**Comment by dcoeurjo** [comment]
and thus disable the parser in travis ?

Ok for this but  if travis complains, it means that for gcc users, the dgtal examples/tools may not compile. 

Maybe we could sort a little bit the WITH_* entries. Some of them are marginal (Patate, ...) others are highly recommended (qglviewer, GMP, poly. parser...).

**Comment by kerautret** [comment]
Yes for the tools we can add a tab in the main DGtalTools info to give the dependance of the tools which will not always be compilled ?or perhaps a message in Cmake indicating that some tools will be missing..

**Comment by dcoeurjo** [comment]
Okay with @JacquesOlivierLachaud 's solution: the bug may be only due to travis VM RAM limit.
Ok with the option set to true by default (expect for travis)

**Comment by dcoeurjo** [comment]
MPolynomial seems to be fine on Travis boost version.. Maybe we don't need such thing. 
Closing
