### ISSUE TITLE
Documentation of SetFromImage::append is incorrect?

### ISSUE THREAD

**Issue by ineol** [DGtal-team/DGtal#998]
It says "Append a Set to an existing image" and "aSet the set (maybe empty) to which points are added", which seems inconsistant.

**Comment by dcoeurjo** [comment]
Oh you're right, just a cut/paste issue in the documentation. I'll fix it.
thanks for the bug report

**Comment by dcoeurjo** [comment]
(pending PR #999)

**Comment by kerautret** [comment]
merged thanks
